// Code generated by tools/expression. DO NOT EDIT.
// Source: schemas/functions/*.yaml

package expressions

// ParamSpec is one declared parameter.
type ParamSpec struct {
	Name     string
	Type     ValueType
	Optional bool
	Variadic bool
}

// FunctionSpec is one declared function.
type FunctionSpec struct {
	Namespace string
	Name      string
	// Qualified is `namespace.name` — how an expression addresses it.
	Qualified string
	Summary   string
	Params    []ParamSpec
	Returns   ValueType
}

// CoreFunctionSpecs is what every implementation is checked against at
// load time. Neither language may add, rename or re-sign a function on its
// own. The registry that pairs these with implementations is CoreFunctions().
var CoreFunctionSpecs = []FunctionSpec{
	{
		Namespace: "dt",
		Name:      "add",
		Qualified: "dt.add",
		Summary:   "Shift an instant. Unit is one of seconds, minutes, hours, days.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeDatetime, Optional: false, Variadic: false},
			{Name: "amount", Type: TypeNumber, Optional: false, Variadic: false},
			{Name: "unit", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeDatetime,
	},
	{
		Namespace: "dt",
		Name:      "diff",
		Qualified: "dt.diff",
		Summary:   "Whole units from the second instant to the first, truncated toward zero.",
		Params: []ParamSpec{
			{Name: "a", Type: TypeDatetime, Optional: false, Variadic: false},
			{Name: "b", Type: TypeDatetime, Optional: false, Variadic: false},
			{Name: "unit", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "dt",
		Name:      "iso",
		Qualified: "dt.iso",
		Summary:   "Render an instant as RFC 3339 in UTC.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeDatetime, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "dt",
		Name:      "now",
		Qualified: "dt.now",
		Summary:   "The current instant, read from the caller-supplied clock.",
		Params:    []ParamSpec{},
		Returns:   TypeDatetime,
	},
	{
		Namespace: "dt",
		Name:      "parse",
		Qualified: "dt.parse",
		Summary:   "Read an RFC 3339 timestamp.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeDatetime,
	},
	{
		Namespace: "json",
		Name:      "parse",
		Qualified: "json.parse",
		Summary:   "Read a JSON document.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeUnknown,
	},
	{
		Namespace: "json",
		Name:      "stringify",
		Qualified: "json.stringify",
		Summary:   "Render a value as compact JSON.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeUnknown, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "list",
		Name:      "contains",
		Qualified: "list.contains",
		Summary:   "Whether the list holds a value equal to the needle, by the same rule as `==`.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
			{Name: "needle", Type: TypeUnknown, Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "list",
		Name:      "first",
		Qualified: "list.first",
		Summary:   "First element, or null when empty.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
		},
		Returns: TypeUnknown,
	},
	{
		Namespace: "list",
		Name:      "join",
		Qualified: "list.join",
		Summary:   "Render each element as text and join with a separator.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
			{Name: "separator", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "list",
		Name:      "last",
		Qualified: "list.last",
		Summary:   "Last element, or null when empty.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
		},
		Returns: TypeUnknown,
	},
	{
		Namespace: "list",
		Name:      "len",
		Qualified: "list.len",
		Summary:   "Number of elements.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "list",
		Name:      "slice",
		Qualified: "list.slice",
		Summary:   "Elements from start up to but not including end.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
			{Name: "start", Type: TypeNumber, Optional: false, Variadic: false},
			{Name: "end", Type: TypeNumber, Optional: true, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "list",
		Name:      "sort",
		Qualified: "list.sort",
		Summary:   "Ascending. Every element must be the same comparable type.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "list",
		Name:      "unique",
		Qualified: "list.unique",
		Summary:   "Elements with later duplicates removed, order preserved.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Optional: false, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "num",
		Name:      "abs",
		Qualified: "num.abs",
		Summary:   "Magnitude.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "ceil",
		Qualified: "num.ceil",
		Summary:   "Smallest whole number not less than the value.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "floor",
		Qualified: "num.floor",
		Summary:   "Largest whole number not greater than the value.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "max",
		Qualified: "num.max",
		Summary:   "Largest of its arguments.",
		Params: []ParamSpec{
			{Name: "values", Type: TypeNumber, Optional: false, Variadic: true},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "min",
		Qualified: "num.min",
		Summary:   "Smallest of its arguments.",
		Params: []ParamSpec{
			{Name: "values", Type: TypeNumber, Optional: false, Variadic: true},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "parse",
		Qualified: "num.parse",
		Summary:   "Read a number from text. This is the only text-to-number conversion; none is implicit.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "round",
		Qualified: "num.round",
		Summary:   "Nearest whole number, halves away from zero.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "text",
		Name:      "concat",
		Qualified: "text.concat",
		Summary:   "Join values end to end. There is no `+` for text.",
		Params: []ParamSpec{
			{Name: "parts", Type: TypeText, Optional: false, Variadic: true},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "contains",
		Qualified: "text.contains",
		Summary:   "Whether the value contains the search string.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
			{Name: "search", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "text",
		Name:      "ends_with",
		Qualified: "text.ends_with",
		Summary:   "Whether the value ends with the suffix.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
			{Name: "suffix", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "text",
		Name:      "join",
		Qualified: "text.join",
		Summary:   "Join a list with a separator.",
		Params: []ParamSpec{
			{Name: "values", Type: TypeList, Optional: false, Variadic: false},
			{Name: "separator", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "len",
		Qualified: "text.len",
		Summary:   "Length in code points.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "text",
		Name:      "lower",
		Qualified: "text.lower",
		Summary:   "Lowercase.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "replace",
		Qualified: "text.replace",
		Summary:   "Replace every occurrence.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
			{Name: "search", Type: TypeText, Optional: false, Variadic: false},
			{Name: "replacement", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "slice",
		Qualified: "text.slice",
		Summary:   "Characters from start up to but not including end. Counted in code points.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
			{Name: "start", Type: TypeNumber, Optional: false, Variadic: false},
			{Name: "end", Type: TypeNumber, Optional: true, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "split",
		Qualified: "text.split",
		Summary:   "Split on a separator.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
			{Name: "separator", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "text",
		Name:      "starts_with",
		Qualified: "text.starts_with",
		Summary:   "Whether the value begins with the prefix.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
			{Name: "prefix", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "text",
		Name:      "trim",
		Qualified: "text.trim",
		Summary:   "Remove leading and trailing whitespace.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "upper",
		Qualified: "text.upper",
		Summary:   "Uppercase.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
}
