// Code generated by tools/expression. DO NOT EDIT.
// Source: schemas/functions/*.yaml

package expressions

// ParamSpec is one declared parameter.
type ParamSpec struct {
	Name string
	Type ValueType
	// Description is one sentence saying what this parameter is for.
	Description string
	Optional    bool
	Variadic    bool
}

// NamespaceSpec is one declared namespace.
type NamespaceSpec struct {
	Namespace string
	// Summary describes the group, shown above its functions.
	Summary string
}

// CoreFunctionNamespaces groups the functions below, for a picker that
// lists a namespace before the functions inside it.
var CoreFunctionNamespaces = []NamespaceSpec{
	{Namespace: "dt", Summary: "Dates and times. Read them, move them forwards or backwards, and measure how far apart two of them are."},
	{Namespace: "json", Summary: "JSON text. Read a value out of it when something arrives as JSON, or write one back to it."},
	{Namespace: "list", Summary: "Lists. Count one, take a piece out of it, sort it, or join it into text. To do something to every item in turn, use a loop step rather than a function."},
	{Namespace: "num", Summary: "Numbers. Dividing always gives a decimal — 7 / 2 is 3.5 — and a half always rounds away from zero, so -0.5 rounds to -1."},
	{Namespace: "text", Summary: "Text. Change its case, trim it, split it, join it, and test what it holds. Changing case works the same everywhere and never depends on a language or region."},
}

// FunctionSpec is one declared function.
type FunctionSpec struct {
	Namespace string
	Name      string
	// Qualified is `namespace.name` — how an expression addresses it.
	Qualified string
	Summary   string
	Params    []ParamSpec
	Returns   ValueType
}

// CoreFunctionSpecs is what every implementation is checked against at
// load time. Neither language may add, rename or re-sign a function on its
// own. The registry that pairs these with implementations is CoreFunctions().
var CoreFunctionSpecs = []FunctionSpec{
	{
		Namespace: "dt",
		Name:      "add",
		Qualified: "dt.add",
		Summary:   "Move a date and time forwards or backwards.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeDatetime, Description: "The date and time to move.", Optional: false, Variadic: false},
			{Name: "amount", Type: TypeNumber, Description: "How many units to move by. A negative amount moves backwards.", Optional: false, Variadic: false},
			{Name: "unit", Type: TypeText, Description: "One of seconds, minutes, hours or days.", Optional: false, Variadic: false},
		},
		Returns: TypeDatetime,
	},
	{
		Namespace: "dt",
		Name:      "diff",
		Qualified: "dt.diff",
		Summary:   "How many whole units separate two dates and times. Anything left over is dropped.",
		Params: []ParamSpec{
			{Name: "a", Type: TypeDatetime, Description: "The date and time measured to.", Optional: false, Variadic: false},
			{Name: "b", Type: TypeDatetime, Description: "The date and time measured from. Later than the first gives a negative answer.", Optional: false, Variadic: false},
			{Name: "unit", Type: TypeText, Description: "One of seconds, minutes, hours or days.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "dt",
		Name:      "iso",
		Qualified: "dt.iso",
		Summary:   "Write a date and time as text, in UTC.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeDatetime, Description: "The date and time to write.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "dt",
		Name:      "now",
		Qualified: "dt.now",
		Summary:   "The date and time this run started.",
		Params:    []ParamSpec{},
		Returns:   TypeDatetime,
	},
	{
		Namespace: "dt",
		Name:      "parse",
		Qualified: "dt.parse",
		Summary:   "Read a date and time from text, written like `2026-08-22T05:14:00Z`.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The date and time to read, written like `2026-08-22T05:14:00Z`.", Optional: false, Variadic: false},
		},
		Returns: TypeDatetime,
	},
	{
		Namespace: "json",
		Name:      "parse",
		Qualified: "json.parse",
		Summary:   "Read a value from JSON text.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The JSON text to read.", Optional: false, Variadic: false},
		},
		Returns: TypeUnknown,
	},
	{
		Namespace: "json",
		Name:      "stringify",
		Qualified: "json.stringify",
		Summary:   "Write a value as JSON text.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeUnknown, Description: "The value to write. Lists and objects are written out whole.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "list",
		Name:      "contains",
		Qualified: "list.contains",
		Summary:   "Whether the list holds this value. Two values match only when they are the same type.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list to search.", Optional: false, Variadic: false},
			{Name: "needle", Type: TypeUnknown, Description: "The value to look for.", Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "list",
		Name:      "first",
		Qualified: "list.first",
		Summary:   "The first item, or null when the list is empty.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list to read from.", Optional: false, Variadic: false},
		},
		Returns: TypeUnknown,
	},
	{
		Namespace: "list",
		Name:      "join",
		Qualified: "list.join",
		Summary:   "Write every item as text, with a separator between them.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list whose items are written out and joined.", Optional: false, Variadic: false},
			{Name: "separator", Type: TypeText, Description: "Goes between items, and never before the first or after the last.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "list",
		Name:      "last",
		Qualified: "list.last",
		Summary:   "The last item, or null when the list is empty.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list to read from.", Optional: false, Variadic: false},
		},
		Returns: TypeUnknown,
	},
	{
		Namespace: "list",
		Name:      "len",
		Qualified: "list.len",
		Summary:   "How many items the list holds.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list to measure.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "list",
		Name:      "slice",
		Qualified: "list.slice",
		Summary:   "The items from one position up to, but not including, another.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list to take items from.", Optional: false, Variadic: false},
			{Name: "start", Type: TypeNumber, Description: "Position of the first item kept, counting from zero.", Optional: false, Variadic: false},
			{Name: "end", Type: TypeNumber, Description: "Position to stop before. Leave it out to run to the end.", Optional: true, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "list",
		Name:      "sort",
		Qualified: "list.sort",
		Summary:   "The list in ascending order. Every item has to be the same kind of value.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list to sort.", Optional: false, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "list",
		Name:      "unique",
		Qualified: "list.unique",
		Summary:   "The list with repeats removed, keeping the first of each and the original order.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeList, Description: "The list to remove repeats from.", Optional: false, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "num",
		Name:      "abs",
		Qualified: "num.abs",
		Summary:   "The number without its sign.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Description: "The number to take the sign off.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "ceil",
		Qualified: "num.ceil",
		Summary:   "The nearest whole number at or above this one.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Description: "The number to round up.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "floor",
		Qualified: "num.floor",
		Summary:   "The nearest whole number at or below this one.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Description: "The number to round down.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "max",
		Qualified: "num.max",
		Summary:   "The largest of the numbers given.",
		Params: []ParamSpec{
			{Name: "values", Type: TypeNumber, Description: "The numbers to compare, each one its own argument.", Optional: false, Variadic: true},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "min",
		Qualified: "num.min",
		Summary:   "The smallest of the numbers given.",
		Params: []ParamSpec{
			{Name: "values", Type: TypeNumber, Description: "The numbers to compare, each one its own argument.", Optional: false, Variadic: true},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "parse",
		Qualified: "num.parse",
		Summary:   "Read a number out of text. Text never becomes a number on its own, so this is how.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to read a number from.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "num",
		Name:      "round",
		Qualified: "num.round",
		Summary:   "The nearest whole number. A half rounds away from zero.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeNumber, Description: "The number to round.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "text",
		Name:      "concat",
		Qualified: "text.concat",
		Summary:   "Join values end to end. `+` adds numbers and never joins text, so this is how text is joined.",
		Params: []ParamSpec{
			{Name: "parts", Type: TypeText, Description: "The pieces to join, in order, each one its own argument.", Optional: false, Variadic: true},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "contains",
		Qualified: "text.contains",
		Summary:   "Whether the text holds this piece somewhere inside it.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to search in.", Optional: false, Variadic: false},
			{Name: "search", Type: TypeText, Description: "The piece to look for.", Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "text",
		Name:      "ends_with",
		Qualified: "text.ends_with",
		Summary:   "Whether the text ends with this piece.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to test.", Optional: false, Variadic: false},
			{Name: "suffix", Type: TypeText, Description: "The piece it should end with.", Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "text",
		Name:      "join",
		Qualified: "text.join",
		Summary:   "Join a list into one piece of text, with a separator between the items.",
		Params: []ParamSpec{
			{Name: "values", Type: TypeList, Description: "The list whose items are joined.", Optional: false, Variadic: false},
			{Name: "separator", Type: TypeText, Description: "Goes between items, and never before the first or after the last.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "len",
		Qualified: "text.len",
		Summary:   "How many characters the text holds.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to measure.", Optional: false, Variadic: false},
		},
		Returns: TypeNumber,
	},
	{
		Namespace: "text",
		Name:      "lower",
		Qualified: "text.lower",
		Summary:   "The text in lower case.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to convert.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "replace",
		Qualified: "text.replace",
		Summary:   "Replace every occurrence, not only the first.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to search in.", Optional: false, Variadic: false},
			{Name: "search", Type: TypeText, Description: "The text to look for. Every occurrence is replaced.", Optional: false, Variadic: false},
			{Name: "replacement", Type: TypeText, Description: "What each occurrence becomes.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "slice",
		Qualified: "text.slice",
		Summary:   "The characters from one position up to, but not including, another.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to take characters from.", Optional: false, Variadic: false},
			{Name: "start", Type: TypeNumber, Description: "Position of the first character kept, counting from zero.", Optional: false, Variadic: false},
			{Name: "end", Type: TypeNumber, Description: "Position to stop before. Leave it out to run to the end.", Optional: true, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "split",
		Qualified: "text.split",
		Summary:   "Break text into a list wherever a separator appears.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to break up.", Optional: false, Variadic: false},
			{Name: "separator", Type: TypeText, Description: "Where to break. It does not appear in the result.", Optional: false, Variadic: false},
		},
		Returns: TypeList,
	},
	{
		Namespace: "text",
		Name:      "starts_with",
		Qualified: "text.starts_with",
		Summary:   "Whether the text begins with this piece.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to test.", Optional: false, Variadic: false},
			{Name: "prefix", Type: TypeText, Description: "The piece it should begin with.", Optional: false, Variadic: false},
		},
		Returns: TypeBoolean,
	},
	{
		Namespace: "text",
		Name:      "trim",
		Qualified: "text.trim",
		Summary:   "The text with any spaces at either end removed.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to trim.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
	{
		Namespace: "text",
		Name:      "upper",
		Qualified: "text.upper",
		Summary:   "The text in upper case.",
		Params: []ParamSpec{
			{Name: "value", Type: TypeText, Description: "The text to convert.", Optional: false, Variadic: false},
		},
		Returns: TypeText,
	},
}
