// Code generated by tools/expression. DO NOT EDIT.
// Source: schemas/diagnostics.yaml

package expressions

// Severity says what a diagnostic does: an error blocks Publish, a warning
// informs and blocks nothing.
type Severity string

const (
	SeverityError   Severity = "error"
	SeverityWarning Severity = "warning"
)

// Phase says when a code can be raised: check is design time, eval is run time.
type Phase string

const (
	PhaseCheck Phase = "check"
	PhaseEval  Phase = "eval"
)

// Code is a stable diagnostic identifier, shared with TypeScript.
type Code string

const (
	CodeExprParseError        Code = "EXPR_PARSE_ERROR"
	CodeExprUnknownReference  Code = "EXPR_UNKNOWN_REFERENCE"
	CodeExprUnknownFunction   Code = "EXPR_UNKNOWN_FUNCTION"
	CodeExprArityMismatch     Code = "EXPR_ARITY_MISMATCH"
	CodeExprArgumentType      Code = "EXPR_ARGUMENT_TYPE"
	CodeExprTypeMismatch      Code = "EXPR_TYPE_MISMATCH"
	CodeExprTypeUnknown       Code = "EXPR_TYPE_UNKNOWN"
	CodeExprOperandType       Code = "EXPR_OPERAND_TYPE"
	CodeExprFunctionCollision Code = "EXPR_FUNCTION_COLLISION"
	CodeEvalMissingPath       Code = "EVAL_MISSING_PATH"
	CodeEvalTypeMismatch      Code = "EVAL_TYPE_MISMATCH"
	CodeEvalOperandType       Code = "EVAL_OPERAND_TYPE"
	CodeEvalCompareNull       Code = "EVAL_COMPARE_NULL"
	CodeEvalCompareTypes      Code = "EVAL_COMPARE_TYPES"
	CodeEvalNumericOverflow   Code = "EVAL_NUMERIC_OVERFLOW"
	CodeEvalDivisionByZero    Code = "EVAL_DIVISION_BY_ZERO"
	CodeEvalUnknownFunction   Code = "EVAL_UNKNOWN_FUNCTION"
	CodeEvalArityMismatch     Code = "EVAL_ARITY_MISMATCH"
	CodeEvalBadArgument       Code = "EVAL_BAD_ARGUMENT"
)

// DiagnosticSpec is one declared code.
type DiagnosticSpec struct {
	Code     Code
	Severity Severity
	Phase    Phase
	// Message is a template; {name} holes are filled by FormatMessage.
	Message string
}

// Diagnostics is the declaration. Severity is part of the shared contract:
// a code that errors in TypeScript and warns here would let a workflow
// publish from one builder and not another.
var Diagnostics = map[Code]DiagnosticSpec{
	CodeExprParseError:        {Code: CodeExprParseError, Severity: SeverityError, Phase: PhaseCheck, Message: "{detail}"},
	CodeExprUnknownReference:  {Code: CodeExprUnknownReference, Severity: SeverityError, Phase: PhaseCheck, Message: "Nothing named {name} is in scope here."},
	CodeExprUnknownFunction:   {Code: CodeExprUnknownFunction, Severity: SeverityError, Phase: PhaseCheck, Message: "There is no function {name}."},
	CodeExprArityMismatch:     {Code: CodeExprArityMismatch, Severity: SeverityError, Phase: PhaseCheck, Message: "{name} takes {expected} arguments, not {actual}."},
	CodeExprArgumentType:      {Code: CodeExprArgumentType, Severity: SeverityError, Phase: PhaseCheck, Message: "{name} expects {expected} for {param}, not {actual}."},
	CodeExprTypeMismatch:      {Code: CodeExprTypeMismatch, Severity: SeverityError, Phase: PhaseCheck, Message: "{name} expects {expected}, but this produces {actual}."},
	CodeExprTypeUnknown:       {Code: CodeExprTypeUnknown, Severity: SeverityWarning, Phase: PhaseCheck, Message: "{name} expects {expected}; this type is only known at run time."},
	CodeExprOperandType:       {Code: CodeExprOperandType, Severity: SeverityError, Phase: PhaseCheck, Message: "{op} expects {expected}, not {actual}."},
	CodeExprFunctionCollision: {Code: CodeExprFunctionCollision, Severity: SeverityError, Phase: PhaseCheck, Message: "{name} is declared twice."},
	CodeEvalMissingPath:       {Code: CodeEvalMissingPath, Severity: SeverityError, Phase: PhaseEval, Message: "{name} is not present."},
	CodeEvalTypeMismatch:      {Code: CodeEvalTypeMismatch, Severity: SeverityError, Phase: PhaseEval, Message: "{name} expects {expected}, but this produced {actual}."},
	CodeEvalOperandType:       {Code: CodeEvalOperandType, Severity: SeverityError, Phase: PhaseEval, Message: "{op} expects {expected}, not {actual}."},
	CodeEvalCompareNull:       {Code: CodeEvalCompareNull, Severity: SeverityError, Phase: PhaseEval, Message: "{op} cannot compare null."},
	CodeEvalCompareTypes:      {Code: CodeEvalCompareTypes, Severity: SeverityError, Phase: PhaseEval, Message: "{op} cannot compare {expected} with {actual}."},
	CodeEvalNumericOverflow:   {Code: CodeEvalNumericOverflow, Severity: SeverityError, Phase: PhaseEval, Message: "{op} produced a number too large to represent."},
	CodeEvalDivisionByZero:    {Code: CodeEvalDivisionByZero, Severity: SeverityError, Phase: PhaseEval, Message: "Division by zero."},
	CodeEvalUnknownFunction:   {Code: CodeEvalUnknownFunction, Severity: SeverityError, Phase: PhaseEval, Message: "There is no function {name}."},
	CodeEvalArityMismatch:     {Code: CodeEvalArityMismatch, Severity: SeverityError, Phase: PhaseEval, Message: "{name} takes {expected} arguments, not {actual}."},
	CodeEvalBadArgument:       {Code: CodeEvalBadArgument, Severity: SeverityError, Phase: PhaseEval, Message: "{name} cannot accept {actual} for {param}."},
}
