// Code generated by pigeon; DO NOT EDIT.

// Code generated by tools/expression. DO NOT EDIT.
package expressions

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Template",
			pos:  position{line: 28, col: 1, offset: 1204},
			expr: &actionExpr{
				pos: position{line: 28, col: 12, offset: 1215},
				run: (*parser).callonTemplate1,
				expr: &seqExpr{
					pos: position{line: 28, col: 12, offset: 1215},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 28, col: 12, offset: 1215},
							label: "segs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 28, col: 17, offset: 1220},
								expr: &ruleRefExpr{
									pos:  position{line: 28, col: 17, offset: 1220},
									name: "Segment",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 26, offset: 1229},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Segment",
			pos:  position{line: 30, col: 1, offset: 1264},
			expr: &choiceExpr{
				pos: position{line: 30, col: 11, offset: 1274},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 30, col: 11, offset: 1274},
						name: "Hole",
					},
					&ruleRefExpr{
						pos:  position{line: 30, col: 18, offset: 1281},
						name: "TextRun",
					},
				},
			},
		},
		{
			name: "Hole",
			pos:  position{line: 32, col: 1, offset: 1290},
			expr: &actionExpr{
				pos: position{line: 32, col: 8, offset: 1297},
				run: (*parser).callonHole1,
				expr: &seqExpr{
					pos: position{line: 32, col: 8, offset: 1297},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 32, col: 8, offset: 1297},
							val:        "{{",
							ignoreCase: false,
							want:       "\"{{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 13, offset: 1302},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 15, offset: 1304},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 18, offset: 1307},
								name: "At",
							},
						},
						&labeledExpr{
							pos:   position{line: 32, col: 21, offset: 1310},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 23, offset: 1312},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 28, offset: 1317},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 32, col: 30, offset: 1319},
							val:        "}}",
							ignoreCase: false,
							want:       "\"}}\"",
						},
					},
				},
			},
		},
		{
			name: "TextRun",
			pos:  position{line: 34, col: 1, offset: 1352},
			expr: &actionExpr{
				pos: position{line: 34, col: 11, offset: 1362},
				run: (*parser).callonTextRun1,
				expr: &labeledExpr{
					pos:   position{line: 34, col: 11, offset: 1362},
					label: "cs",
					expr: &oneOrMoreExpr{
						pos: position{line: 34, col: 14, offset: 1365},
						expr: &ruleRefExpr{
							pos:  position{line: 34, col: 14, offset: 1365},
							name: "TextChar",
						},
					},
				},
			},
		},
		{
			name: "TextChar",
			pos:  position{line: 36, col: 1, offset: 1400},
			expr: &actionExpr{
				pos: position{line: 36, col: 12, offset: 1411},
				run: (*parser).callonTextChar1,
				expr: &seqExpr{
					pos: position{line: 36, col: 12, offset: 1411},
					exprs: []any{
						&notExpr{
							pos: position{line: 36, col: 12, offset: 1411},
							expr: &litMatcher{
								pos:        position{line: 36, col: 13, offset: 1412},
								val:        "{{",
								ignoreCase: false,
								want:       "\"{{\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 36, col: 18, offset: 1417},
							label: "ch",
							expr: &anyMatcher{
								line: 36, col: 21, offset: 1420,
							},
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 40, col: 1, offset: 1523},
			expr: &ruleRefExpr{
				pos:  position{line: 40, col: 8, offset: 1530},
				name: "Ternary",
			},
		},
		{
			name: "Ternary",
			pos:  position{line: 42, col: 1, offset: 1539},
			expr: &actionExpr{
				pos: position{line: 42, col: 11, offset: 1549},
				run: (*parser).callonTernary1,
				expr: &seqExpr{
					pos: position{line: 42, col: 11, offset: 1549},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 42, col: 11, offset: 1549},
							label: "cond",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 16, offset: 1554},
								name: "Coalesce",
							},
						},
						&labeledExpr{
							pos:   position{line: 42, col: 25, offset: 1563},
							label: "t",
							expr: &zeroOrOneExpr{
								pos: position{line: 42, col: 27, offset: 1565},
								expr: &seqExpr{
									pos: position{line: 42, col: 29, offset: 1567},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 42, col: 29, offset: 1567},
											name: "QMark",
										},
										&ruleRefExpr{
											pos:  position{line: 42, col: 35, offset: 1573},
											name: "Ternary",
										},
										&ruleRefExpr{
											pos:  position{line: 42, col: 43, offset: 1581},
											name: "Colon",
										},
										&ruleRefExpr{
											pos:  position{line: 42, col: 49, offset: 1587},
											name: "Ternary",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Coalesce",
			pos:  position{line: 44, col: 1, offset: 1631},
			expr: &actionExpr{
				pos: position{line: 44, col: 12, offset: 1642},
				run: (*parser).callonCoalesce1,
				expr: &seqExpr{
					pos: position{line: 44, col: 12, offset: 1642},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 44, col: 12, offset: 1642},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 14, offset: 1644},
								name: "Or",
							},
						},
						&labeledExpr{
							pos:   position{line: 44, col: 17, offset: 1647},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 44, col: 19, offset: 1649},
								expr: &seqExpr{
									pos: position{line: 44, col: 21, offset: 1651},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 44, col: 21, offset: 1651},
											name: "CoalesceOp",
										},
										&ruleRefExpr{
											pos:  position{line: 44, col: 32, offset: 1662},
											name: "Or",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Or",
			pos:  position{line: 46, col: 1, offset: 1697},
			expr: &actionExpr{
				pos: position{line: 46, col: 6, offset: 1702},
				run: (*parser).callonOr1,
				expr: &seqExpr{
					pos: position{line: 46, col: 6, offset: 1702},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 46, col: 6, offset: 1702},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 8, offset: 1704},
								name: "And",
							},
						},
						&labeledExpr{
							pos:   position{line: 46, col: 12, offset: 1708},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 46, col: 14, offset: 1710},
								expr: &seqExpr{
									pos: position{line: 46, col: 16, offset: 1712},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 46, col: 16, offset: 1712},
											name: "OrOp",
										},
										&ruleRefExpr{
											pos:  position{line: 46, col: 21, offset: 1717},
											name: "And",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "And",
			pos:  position{line: 48, col: 1, offset: 1753},
			expr: &actionExpr{
				pos: position{line: 48, col: 7, offset: 1759},
				run: (*parser).callonAnd1,
				expr: &seqExpr{
					pos: position{line: 48, col: 7, offset: 1759},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 48, col: 7, offset: 1759},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 48, col: 9, offset: 1761},
								name: "Equality",
							},
						},
						&labeledExpr{
							pos:   position{line: 48, col: 18, offset: 1770},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 48, col: 20, offset: 1772},
								expr: &seqExpr{
									pos: position{line: 48, col: 22, offset: 1774},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 48, col: 22, offset: 1774},
											name: "AndOp",
										},
										&ruleRefExpr{
											pos:  position{line: 48, col: 28, offset: 1780},
											name: "Equality",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Equality",
			pos:  position{line: 50, col: 1, offset: 1821},
			expr: &actionExpr{
				pos: position{line: 50, col: 12, offset: 1832},
				run: (*parser).callonEquality1,
				expr: &seqExpr{
					pos: position{line: 50, col: 12, offset: 1832},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 50, col: 12, offset: 1832},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 14, offset: 1834},
								name: "Relational",
							},
						},
						&labeledExpr{
							pos:   position{line: 50, col: 25, offset: 1845},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 50, col: 27, offset: 1847},
								expr: &seqExpr{
									pos: position{line: 50, col: 29, offset: 1849},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 50, col: 29, offset: 1849},
											name: "EqualityOp",
										},
										&ruleRefExpr{
											pos:  position{line: 50, col: 40, offset: 1860},
											name: "Relational",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Relational",
			pos:  position{line: 52, col: 1, offset: 1903},
			expr: &actionExpr{
				pos: position{line: 52, col: 14, offset: 1916},
				run: (*parser).callonRelational1,
				expr: &seqExpr{
					pos: position{line: 52, col: 14, offset: 1916},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 52, col: 14, offset: 1916},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 16, offset: 1918},
								name: "Additive",
							},
						},
						&labeledExpr{
							pos:   position{line: 52, col: 25, offset: 1927},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 52, col: 27, offset: 1929},
								expr: &seqExpr{
									pos: position{line: 52, col: 29, offset: 1931},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 52, col: 29, offset: 1931},
											name: "RelationalOp",
										},
										&ruleRefExpr{
											pos:  position{line: 52, col: 42, offset: 1944},
											name: "Additive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Additive",
			pos:  position{line: 54, col: 1, offset: 1985},
			expr: &actionExpr{
				pos: position{line: 54, col: 12, offset: 1996},
				run: (*parser).callonAdditive1,
				expr: &seqExpr{
					pos: position{line: 54, col: 12, offset: 1996},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 54, col: 12, offset: 1996},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 14, offset: 1998},
								name: "Multiplicative",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 29, offset: 2013},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 54, col: 31, offset: 2015},
								expr: &seqExpr{
									pos: position{line: 54, col: 33, offset: 2017},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 54, col: 33, offset: 2017},
											name: "AdditiveOp",
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 44, offset: 2028},
											name: "Multiplicative",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Multiplicative",
			pos:  position{line: 56, col: 1, offset: 2075},
			expr: &actionExpr{
				pos: position{line: 56, col: 18, offset: 2092},
				run: (*parser).callonMultiplicative1,
				expr: &seqExpr{
					pos: position{line: 56, col: 18, offset: 2092},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 56, col: 18, offset: 2092},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 20, offset: 2094},
								name: "Unary",
							},
						},
						&labeledExpr{
							pos:   position{line: 56, col: 26, offset: 2100},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 56, col: 28, offset: 2102},
								expr: &seqExpr{
									pos: position{line: 56, col: 30, offset: 2104},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 56, col: 30, offset: 2104},
											name: "MultiplicativeOp",
										},
										&ruleRefExpr{
											pos:  position{line: 56, col: 47, offset: 2121},
											name: "Unary",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Unary",
			pos:  position{line: 58, col: 1, offset: 2159},
			expr: &choiceExpr{
				pos: position{line: 58, col: 9, offset: 2167},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 58, col: 9, offset: 2167},
						run: (*parser).callonUnary2,
						expr: &seqExpr{
							pos: position{line: 58, col: 9, offset: 2167},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 58, col: 9, offset: 2167},
									label: "at",
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 12, offset: 2170},
										name: "At",
									},
								},
								&labeledExpr{
									pos:   position{line: 58, col: 15, offset: 2173},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 18, offset: 2176},
										name: "UnaryOp",
									},
								},
								&labeledExpr{
									pos:   position{line: 58, col: 26, offset: 2184},
									label: "operand",
									expr: &ruleRefExpr{
										pos:  position{line: 58, col: 34, offset: 2192},
										name: "Unary",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 59, col: 9, offset: 2244},
						name: "Postfix",
					},
				},
			},
		},
		{
			name: "Postfix",
			pos:  position{line: 61, col: 1, offset: 2253},
			expr: &actionExpr{
				pos: position{line: 61, col: 11, offset: 2263},
				run: (*parser).callonPostfix1,
				expr: &seqExpr{
					pos: position{line: 61, col: 11, offset: 2263},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 61, col: 11, offset: 2263},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 16, offset: 2268},
								name: "Primary",
							},
						},
						&labeledExpr{
							pos:   position{line: 61, col: 24, offset: 2276},
							label: "sfx",
							expr: &zeroOrMoreExpr{
								pos: position{line: 61, col: 28, offset: 2280},
								expr: &ruleRefExpr{
									pos:  position{line: 61, col: 28, offset: 2280},
									name: "Suffix",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Primary",
			pos:  position{line: 63, col: 1, offset: 2323},
			expr: &choiceExpr{
				pos: position{line: 63, col: 11, offset: 2333},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 63, col: 11, offset: 2333},
						name: "ParenExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 11, offset: 2353},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 65, col: 11, offset: 2371},
						name: "NameRef",
					},
				},
			},
		},
		{
			name: "ParenExpr",
			pos:  position{line: 67, col: 1, offset: 2380},
			expr: &actionExpr{
				pos: position{line: 67, col: 13, offset: 2392},
				run: (*parser).callonParenExpr1,
				expr: &seqExpr{
					pos: position{line: 67, col: 13, offset: 2392},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 67, col: 13, offset: 2392},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 17, offset: 2396},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 67, col: 19, offset: 2398},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 21, offset: 2400},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 67, col: 26, offset: 2405},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 67, col: 28, offset: 2407},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "QMark",
			pos:  position{line: 74, col: 1, offset: 2679},
			expr: &seqExpr{
				pos: position{line: 74, col: 9, offset: 2687},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 74, col: 9, offset: 2687},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 74, col: 11, offset: 2689},
						val:        "?",
						ignoreCase: false,
						want:       "\"?\"",
					},
					&notExpr{
						pos: position{line: 74, col: 15, offset: 2693},
						expr: &litMatcher{
							pos:        position{line: 74, col: 16, offset: 2694},
							val:        "?",
							ignoreCase: false,
							want:       "\"?\"",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 74, col: 20, offset: 2698},
						name: "_",
					},
				},
			},
		},
		{
			name: "Colon",
			pos:  position{line: 75, col: 1, offset: 2700},
			expr: &seqExpr{
				pos: position{line: 75, col: 9, offset: 2708},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 75, col: 9, offset: 2708},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 75, col: 11, offset: 2710},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 15, offset: 2714},
						name: "_",
					},
				},
			},
		},
		{
			name: "CoalesceOp",
			pos:  position{line: 77, col: 1, offset: 2717},
			expr: &actionExpr{
				pos: position{line: 77, col: 20, offset: 2736},
				run: (*parser).callonCoalesceOp1,
				expr: &seqExpr{
					pos: position{line: 77, col: 20, offset: 2736},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 77, col: 20, offset: 2736},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 77, col: 22, offset: 2738},
							label: "op",
							expr: &litMatcher{
								pos:        position{line: 77, col: 25, offset: 2741},
								val:        "??",
								ignoreCase: false,
								want:       "\"??\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 77, col: 30, offset: 2746},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "OrOp",
			pos:  position{line: 78, col: 1, offset: 2799},
			expr: &actionExpr{
				pos: position{line: 78, col: 20, offset: 2818},
				run: (*parser).callonOrOp1,
				expr: &seqExpr{
					pos: position{line: 78, col: 20, offset: 2818},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 78, col: 20, offset: 2818},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 78, col: 22, offset: 2820},
							label: "op",
							expr: &litMatcher{
								pos:        position{line: 78, col: 25, offset: 2823},
								val:        "||",
								ignoreCase: false,
								want:       "\"||\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 78, col: 30, offset: 2828},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "AndOp",
			pos:  position{line: 79, col: 1, offset: 2881},
			expr: &actionExpr{
				pos: position{line: 79, col: 20, offset: 2900},
				run: (*parser).callonAndOp1,
				expr: &seqExpr{
					pos: position{line: 79, col: 20, offset: 2900},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 79, col: 20, offset: 2900},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 79, col: 22, offset: 2902},
							label: "op",
							expr: &litMatcher{
								pos:        position{line: 79, col: 25, offset: 2905},
								val:        "&&",
								ignoreCase: false,
								want:       "\"&&\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 30, offset: 2910},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "EqualityOp",
			pos:  position{line: 80, col: 1, offset: 2963},
			expr: &actionExpr{
				pos: position{line: 80, col: 20, offset: 2982},
				run: (*parser).callonEqualityOp1,
				expr: &seqExpr{
					pos: position{line: 80, col: 20, offset: 2982},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 80, col: 20, offset: 2982},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 80, col: 22, offset: 2984},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 80, col: 26, offset: 2988},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 80, col: 26, offset: 2988},
										val:        "==",
										ignoreCase: false,
										want:       "\"==\"",
									},
									&litMatcher{
										pos:        position{line: 80, col: 33, offset: 2995},
										val:        "!=",
										ignoreCase: false,
										want:       "\"!=\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 80, col: 39, offset: 3001},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "RelationalOp",
			pos:  position{line: 81, col: 1, offset: 3045},
			expr: &actionExpr{
				pos: position{line: 81, col: 20, offset: 3064},
				run: (*parser).callonRelationalOp1,
				expr: &seqExpr{
					pos: position{line: 81, col: 20, offset: 3064},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 81, col: 20, offset: 3064},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 81, col: 22, offset: 3066},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 81, col: 26, offset: 3070},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 81, col: 26, offset: 3070},
										val:        "<=",
										ignoreCase: false,
										want:       "\"<=\"",
									},
									&litMatcher{
										pos:        position{line: 81, col: 33, offset: 3077},
										val:        ">=",
										ignoreCase: false,
										want:       "\">=\"",
									},
									&litMatcher{
										pos:        position{line: 81, col: 40, offset: 3084},
										val:        "<",
										ignoreCase: false,
										want:       "\"<\"",
									},
									&litMatcher{
										pos:        position{line: 81, col: 46, offset: 3090},
										val:        ">",
										ignoreCase: false,
										want:       "\">\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 81, col: 51, offset: 3095},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "AdditiveOp",
			pos:  position{line: 82, col: 1, offset: 3127},
			expr: &actionExpr{
				pos: position{line: 82, col: 20, offset: 3146},
				run: (*parser).callonAdditiveOp1,
				expr: &seqExpr{
					pos: position{line: 82, col: 20, offset: 3146},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 82, col: 20, offset: 3146},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 22, offset: 3148},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 82, col: 26, offset: 3152},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 82, col: 26, offset: 3152},
										val:        "+",
										ignoreCase: false,
										want:       "\"+\"",
									},
									&litMatcher{
										pos:        position{line: 82, col: 32, offset: 3158},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 37, offset: 3163},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "MultiplicativeOp",
			pos:  position{line: 83, col: 1, offset: 3209},
			expr: &actionExpr{
				pos: position{line: 83, col: 20, offset: 3228},
				run: (*parser).callonMultiplicativeOp1,
				expr: &seqExpr{
					pos: position{line: 83, col: 20, offset: 3228},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 83, col: 20, offset: 3228},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 83, col: 22, offset: 3230},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 83, col: 26, offset: 3234},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 83, col: 26, offset: 3234},
										val:        "*",
										ignoreCase: false,
										want:       "\"*\"",
									},
									&litMatcher{
										pos:        position{line: 83, col: 32, offset: 3240},
										val:        "/",
										ignoreCase: false,
										want:       "\"/\"",
									},
									&litMatcher{
										pos:        position{line: 83, col: 38, offset: 3246},
										val:        "%",
										ignoreCase: false,
										want:       "\"%\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 83, col: 43, offset: 3251},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "UnaryOp",
			pos:  position{line: 84, col: 1, offset: 3291},
			expr: &actionExpr{
				pos: position{line: 84, col: 20, offset: 3310},
				run: (*parser).callonUnaryOp1,
				expr: &seqExpr{
					pos: position{line: 84, col: 20, offset: 3310},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 84, col: 20, offset: 3310},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 84, col: 24, offset: 3314},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 84, col: 24, offset: 3314},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 84, col: 24, offset: 3314},
												val:        "!",
												ignoreCase: false,
												want:       "\"!\"",
											},
											&notExpr{
												pos: position{line: 84, col: 28, offset: 3318},
												expr: &litMatcher{
													pos:        position{line: 84, col: 29, offset: 3319},
													val:        "=",
													ignoreCase: false,
													want:       "\"=\"",
												},
											},
										},
									},
									&litMatcher{
										pos:        position{line: 84, col: 35, offset: 3325},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 84, col: 40, offset: 3330},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Suffix",
			pos:  position{line: 88, col: 1, offset: 3455},
			expr: &choiceExpr{
				pos: position{line: 88, col: 10, offset: 3464},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 88, col: 10, offset: 3464},
						name: "MemberSuffix",
					},
					&ruleRefExpr{
						pos:  position{line: 88, col: 25, offset: 3479},
						name: "ProjectSuffix",
					},
					&ruleRefExpr{
						pos:  position{line: 88, col: 41, offset: 3495},
						name: "IndexSuffix",
					},
					&ruleRefExpr{
						pos:  position{line: 88, col: 55, offset: 3509},
						name: "CallSuffix",
					},
				},
			},
		},
		{
			name: "MemberSuffix",
			pos:  position{line: 90, col: 1, offset: 3521},
			expr: &actionExpr{
				pos: position{line: 90, col: 17, offset: 3537},
				run: (*parser).callonMemberSuffix1,
				expr: &seqExpr{
					pos: position{line: 90, col: 17, offset: 3537},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 90, col: 17, offset: 3537},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 90, col: 20, offset: 3540},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 90, col: 23, offset: 3543},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 90, col: 27, offset: 3547},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 90, col: 29, offset: 3549},
								name: "Name",
							},
						},
					},
				},
			},
		},
		{
			name: "ProjectSuffix",
			pos:  position{line: 91, col: 1, offset: 3607},
			expr: &actionExpr{
				pos: position{line: 91, col: 17, offset: 3623},
				run: (*parser).callonProjectSuffix1,
				expr: &seqExpr{
					pos: position{line: 91, col: 17, offset: 3623},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 91, col: 17, offset: 3623},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 91, col: 20, offset: 3626},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 91, col: 23, offset: 3629},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 91, col: 27, offset: 3633},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 91, col: 29, offset: 3635},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "IndexSuffix",
			pos:  position{line: 92, col: 1, offset: 3691},
			expr: &actionExpr{
				pos: position{line: 92, col: 17, offset: 3707},
				run: (*parser).callonIndexSuffix1,
				expr: &seqExpr{
					pos: position{line: 92, col: 17, offset: 3707},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 92, col: 17, offset: 3707},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 20, offset: 3710},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 92, col: 23, offset: 3713},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 27, offset: 3717},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 29, offset: 3719},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 92, col: 31, offset: 3721},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 36, offset: 3726},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 92, col: 38, offset: 3728},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "CallSuffix",
			pos:  position{line: 93, col: 1, offset: 3776},
			expr: &actionExpr{
				pos: position{line: 93, col: 17, offset: 3792},
				run: (*parser).callonCallSuffix1,
				expr: &seqExpr{
					pos: position{line: 93, col: 17, offset: 3792},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 93, col: 17, offset: 3792},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 93, col: 20, offset: 3795},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 93, col: 23, offset: 3798},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 93, col: 27, offset: 3802},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 93, col: 29, offset: 3804},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 93, col: 34, offset: 3809},
								expr: &ruleRefExpr{
									pos:  position{line: 93, col: 34, offset: 3809},
									name: "Args",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 93, col: 40, offset: 3815},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 93, col: 42, offset: 3817},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Args",
			pos:  position{line: 95, col: 1, offset: 3864},
			expr: &actionExpr{
				pos: position{line: 95, col: 8, offset: 3871},
				run: (*parser).callonArgs1,
				expr: &seqExpr{
					pos: position{line: 95, col: 8, offset: 3871},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 95, col: 8, offset: 3871},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 10, offset: 3873},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 95, col: 15, offset: 3878},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 95, col: 17, offset: 3880},
								expr: &seqExpr{
									pos: position{line: 95, col: 19, offset: 3882},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 95, col: 19, offset: 3882},
											name: "Comma",
										},
										&ruleRefExpr{
											pos:  position{line: 95, col: 25, offset: 3888},
											name: "Expr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Comma",
			pos:  position{line: 97, col: 1, offset: 3922},
			expr: &seqExpr{
				pos: position{line: 97, col: 9, offset: 3930},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 97, col: 9, offset: 3930},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 97, col: 11, offset: 3932},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&ruleRefExpr{
						pos:  position{line: 97, col: 15, offset: 3936},
						name: "_",
					},
				},
			},
		},
		{
			name: "NameRef",
			pos:  position{line: 101, col: 1, offset: 4020},
			expr: &actionExpr{
				pos: position{line: 101, col: 11, offset: 4030},
				run: (*parser).callonNameRef1,
				expr: &seqExpr{
					pos: position{line: 101, col: 11, offset: 4030},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 101, col: 11, offset: 4030},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 14, offset: 4033},
								name: "At",
							},
						},
						&notExpr{
							pos: position{line: 101, col: 17, offset: 4036},
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 18, offset: 4037},
								name: "ReservedWord",
							},
						},
						&labeledExpr{
							pos:   position{line: 101, col: 31, offset: 4050},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 33, offset: 4052},
								name: "Name",
							},
						},
					},
				},
			},
		},
		{
			name: "Name",
			pos:  position{line: 103, col: 1, offset: 4085},
			expr: &actionExpr{
				pos: position{line: 103, col: 8, offset: 4092},
				run: (*parser).callonName1,
				expr: &seqExpr{
					pos: position{line: 103, col: 8, offset: 4092},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 103, col: 8, offset: 4092},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 10, offset: 4094},
								name: "NameStart",
							},
						},
						&labeledExpr{
							pos:   position{line: 103, col: 20, offset: 4104},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 103, col: 22, offset: 4106},
								expr: &ruleRefExpr{
									pos:  position{line: 103, col: 22, offset: 4106},
									name: "NamePart",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NameStart",
			pos:  position{line: 105, col: 1, offset: 4138},
			expr: &charClassMatcher{
				pos:        position{line: 105, col: 13, offset: 4150},
				val:        "[a-zA-Z_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NamePart",
			pos:  position{line: 106, col: 1, offset: 4160},
			expr: &charClassMatcher{
				pos:        position{line: 106, col: 13, offset: 4172},
				val:        "[a-zA-Z0-9_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "ReservedWord",
			pos:  position{line: 108, col: 1, offset: 4186},
			expr: &seqExpr{
				pos: position{line: 108, col: 16, offset: 4201},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 108, col: 17, offset: 4202},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 108, col: 17, offset: 4202},
								val:        "true",
								ignoreCase: false,
								want:       "\"true\"",
							},
							&litMatcher{
								pos:        position{line: 108, col: 26, offset: 4211},
								val:        "false",
								ignoreCase: false,
								want:       "\"false\"",
							},
							&litMatcher{
								pos:        position{line: 108, col: 36, offset: 4221},
								val:        "null",
								ignoreCase: false,
								want:       "\"null\"",
							},
						},
					},
					&notExpr{
						pos: position{line: 108, col: 44, offset: 4229},
						expr: &ruleRefExpr{
							pos:  position{line: 108, col: 45, offset: 4230},
							name: "NamePart",
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 112, col: 1, offset: 4321},
			expr: &choiceExpr{
				pos: position{line: 112, col: 11, offset: 4331},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 112, col: 11, offset: 4331},
						name: "NullLit",
					},
					&ruleRefExpr{
						pos:  position{line: 112, col: 21, offset: 4341},
						name: "BoolLit",
					},
					&ruleRefExpr{
						pos:  position{line: 112, col: 31, offset: 4351},
						name: "NumberLit",
					},
					&ruleRefExpr{
						pos:  position{line: 112, col: 43, offset: 4363},
						name: "StringLit",
					},
				},
			},
		},
		{
			name: "NullLit",
			pos:  position{line: 114, col: 1, offset: 4374},
			expr: &actionExpr{
				pos: position{line: 114, col: 11, offset: 4384},
				run: (*parser).callonNullLit1,
				expr: &seqExpr{
					pos: position{line: 114, col: 11, offset: 4384},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 114, col: 11, offset: 4384},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 114, col: 14, offset: 4387},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 114, col: 17, offset: 4390},
							val:        "null",
							ignoreCase: false,
							want:       "\"null\"",
						},
						&notExpr{
							pos: position{line: 114, col: 24, offset: 4397},
							expr: &ruleRefExpr{
								pos:  position{line: 114, col: 25, offset: 4398},
								name: "NamePart",
							},
						},
					},
				},
			},
		},
		{
			name: "BoolLit",
			pos:  position{line: 115, col: 1, offset: 4444},
			expr: &actionExpr{
				pos: position{line: 115, col: 11, offset: 4454},
				run: (*parser).callonBoolLit1,
				expr: &seqExpr{
					pos: position{line: 115, col: 11, offset: 4454},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 115, col: 11, offset: 4454},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 14, offset: 4457},
								name: "At",
							},
						},
						&labeledExpr{
							pos:   position{line: 115, col: 17, offset: 4460},
							label: "v",
							expr: &choiceExpr{
								pos: position{line: 115, col: 20, offset: 4463},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 115, col: 20, offset: 4463},
										val:        "true",
										ignoreCase: false,
										want:       "\"true\"",
									},
									&litMatcher{
										pos:        position{line: 115, col: 29, offset: 4472},
										val:        "false",
										ignoreCase: false,
										want:       "\"false\"",
									},
								},
							},
						},
						&notExpr{
							pos: position{line: 115, col: 38, offset: 4481},
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 39, offset: 4482},
								name: "NamePart",
							},
						},
					},
				},
			},
		},
		{
			name: "NumberLit",
			pos:  position{line: 117, col: 1, offset: 4519},
			expr: &actionExpr{
				pos: position{line: 117, col: 13, offset: 4531},
				run: (*parser).callonNumberLit1,
				expr: &seqExpr{
					pos: position{line: 117, col: 13, offset: 4531},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 117, col: 13, offset: 4531},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 16, offset: 4534},
								name: "At",
							},
						},
						&labeledExpr{
							pos:   position{line: 117, col: 19, offset: 4537},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 21, offset: 4539},
								name: "Digits",
							},
						},
						&labeledExpr{
							pos:   position{line: 117, col: 28, offset: 4546},
							label: "f",
							expr: &zeroOrOneExpr{
								pos: position{line: 117, col: 30, offset: 4548},
								expr: &ruleRefExpr{
									pos:  position{line: 117, col: 30, offset: 4548},
									name: "Frac",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 117, col: 36, offset: 4554},
							label: "e",
							expr: &zeroOrOneExpr{
								pos: position{line: 117, col: 38, offset: 4556},
								expr: &ruleRefExpr{
									pos:  position{line: 117, col: 38, offset: 4556},
									name: "Exp",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Digits",
			pos:  position{line: 119, col: 1, offset: 4597},
			expr: &actionExpr{
				pos: position{line: 119, col: 10, offset: 4606},
				run: (*parser).callonDigits1,
				expr: &labeledExpr{
					pos:   position{line: 119, col: 10, offset: 4606},
					label: "d",
					expr: &oneOrMoreExpr{
						pos: position{line: 119, col: 12, offset: 4608},
						expr: &ruleRefExpr{
							pos:  position{line: 119, col: 12, offset: 4608},
							name: "NumPart",
						},
					},
				},
			},
		},
		{
			name: "NumPart",
			pos:  position{line: 120, col: 1, offset: 4635},
			expr: &charClassMatcher{
				pos:        position{line: 120, col: 11, offset: 4645},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Frac",
			pos:  position{line: 121, col: 1, offset: 4651},
			expr: &actionExpr{
				pos: position{line: 121, col: 8, offset: 4658},
				run: (*parser).callonFrac1,
				expr: &seqExpr{
					pos: position{line: 121, col: 8, offset: 4658},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 121, col: 8, offset: 4658},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 121, col: 12, offset: 4662},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 121, col: 14, offset: 4664},
								name: "Digits",
							},
						},
					},
				},
			},
		},
		{
			name: "Exp",
			pos:  position{line: 122, col: 1, offset: 4702},
			expr: &actionExpr{
				pos: position{line: 122, col: 8, offset: 4709},
				run: (*parser).callonExp1,
				expr: &seqExpr{
					pos: position{line: 122, col: 8, offset: 4709},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 122, col: 8, offset: 4709},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 122, col: 10, offset: 4711},
								name: "ExpMark",
							},
						},
						&labeledExpr{
							pos:   position{line: 122, col: 18, offset: 4719},
							label: "s",
							expr: &zeroOrOneExpr{
								pos: position{line: 122, col: 20, offset: 4721},
								expr: &ruleRefExpr{
									pos:  position{line: 122, col: 20, offset: 4721},
									name: "Sign",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 122, col: 26, offset: 4727},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 122, col: 28, offset: 4729},
								name: "Digits",
							},
						},
					},
				},
			},
		},
		{
			name: "ExpMark",
			pos:  position{line: 123, col: 1, offset: 4760},
			expr: &charClassMatcher{
				pos:        position{line: 123, col: 11, offset: 4770},
				val:        "[eE]",
				chars:      []rune{'e', 'E'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Sign",
			pos:  position{line: 124, col: 1, offset: 4775},
			expr: &charClassMatcher{
				pos:        position{line: 124, col: 8, offset: 4782},
				val:        "[+-]",
				chars:      []rune{'+', '-'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "StringLit",
			pos:  position{line: 126, col: 1, offset: 4788},
			expr: &choiceExpr{
				pos: position{line: 126, col: 13, offset: 4800},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 126, col: 13, offset: 4800},
						run: (*parser).callonStringLit2,
						expr: &seqExpr{
							pos: position{line: 126, col: 13, offset: 4800},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 126, col: 13, offset: 4800},
									label: "at",
									expr: &ruleRefExpr{
										pos:  position{line: 126, col: 16, offset: 4803},
										name: "At",
									},
								},
								&litMatcher{
									pos:        position{line: 126, col: 19, offset: 4806},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
								&labeledExpr{
									pos:   position{line: 126, col: 23, offset: 4810},
									label: "cs",
									expr: &zeroOrMoreExpr{
										pos: position{line: 126, col: 26, offset: 4813},
										expr: &ruleRefExpr{
											pos:  position{line: 126, col: 26, offset: 4813},
											name: "SqChar",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 126, col: 34, offset: 4821},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 127, col: 13, offset: 4869},
						run: (*parser).callonStringLit11,
						expr: &seqExpr{
							pos: position{line: 127, col: 13, offset: 4869},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 127, col: 13, offset: 4869},
									label: "at",
									expr: &ruleRefExpr{
										pos:  position{line: 127, col: 16, offset: 4872},
										name: "At",
									},
								},
								&litMatcher{
									pos:        position{line: 127, col: 19, offset: 4875},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&labeledExpr{
									pos:   position{line: 127, col: 24, offset: 4880},
									label: "cs",
									expr: &zeroOrMoreExpr{
										pos: position{line: 127, col: 27, offset: 4883},
										expr: &ruleRefExpr{
											pos:  position{line: 127, col: 27, offset: 4883},
											name: "DqChar",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 127, col: 35, offset: 4891},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SqChar",
			pos:  position{line: 129, col: 1, offset: 4927},
			expr: &choiceExpr{
				pos: position{line: 129, col: 10, offset: 4936},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 129, col: 10, offset: 4936},
						name: "Escape",
					},
					&actionExpr{
						pos: position{line: 129, col: 19, offset: 4945},
						run: (*parser).callonSqChar3,
						expr: &seqExpr{
							pos: position{line: 129, col: 19, offset: 4945},
							exprs: []any{
								&notExpr{
									pos: position{line: 129, col: 19, offset: 4945},
									expr: &litMatcher{
										pos:        position{line: 129, col: 20, offset: 4946},
										val:        "'",
										ignoreCase: false,
										want:       "\"'\"",
									},
								},
								&notExpr{
									pos: position{line: 129, col: 24, offset: 4950},
									expr: &litMatcher{
										pos:        position{line: 129, col: 25, offset: 4951},
										val:        "\\",
										ignoreCase: false,
										want:       "\"\\\\\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 129, col: 30, offset: 4956},
									label: "ch",
									expr: &anyMatcher{
										line: 129, col: 33, offset: 4959,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DqChar",
			pos:  position{line: 130, col: 1, offset: 4980},
			expr: &choiceExpr{
				pos: position{line: 130, col: 10, offset: 4989},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 130, col: 10, offset: 4989},
						name: "Escape",
					},
					&actionExpr{
						pos: position{line: 130, col: 19, offset: 4998},
						run: (*parser).callonDqChar3,
						expr: &seqExpr{
							pos: position{line: 130, col: 19, offset: 4998},
							exprs: []any{
								&notExpr{
									pos: position{line: 130, col: 19, offset: 4998},
									expr: &litMatcher{
										pos:        position{line: 130, col: 20, offset: 4999},
										val:        "\"",
										ignoreCase: false,
										want:       "\"\\\"\"",
									},
								},
								&notExpr{
									pos: position{line: 130, col: 25, offset: 5004},
									expr: &litMatcher{
										pos:        position{line: 130, col: 26, offset: 5005},
										val:        "\\",
										ignoreCase: false,
										want:       "\"\\\\\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 130, col: 31, offset: 5010},
									label: "ch",
									expr: &anyMatcher{
										line: 130, col: 34, offset: 5013,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Escape",
			pos:  position{line: 132, col: 1, offset: 5035},
			expr: &actionExpr{
				pos: position{line: 132, col: 10, offset: 5044},
				run: (*parser).callonEscape1,
				expr: &seqExpr{
					pos: position{line: 132, col: 10, offset: 5044},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 132, col: 10, offset: 5044},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&labeledExpr{
							pos:   position{line: 132, col: 15, offset: 5049},
							label: "ch",
							expr: &anyMatcher{
								line: 132, col: 18, offset: 5052,
							},
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 136, col: 1, offset: 5162},
			expr: &zeroOrMoreExpr{
				pos: position{line: 136, col: 5, offset: 5166},
				expr: &ruleRefExpr{
					pos:  position{line: 136, col: 5, offset: 5166},
					name: "Space",
				},
			},
		},
		{
			name: "Space",
			pos:  position{line: 137, col: 1, offset: 5173},
			expr: &charClassMatcher{
				pos:        position{line: 137, col: 9, offset: 5181},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 139, col: 1, offset: 5192},
			expr: &notExpr{
				pos: position{line: 139, col: 7, offset: 5198},
				expr: &anyMatcher{
					line: 139, col: 8, offset: 5199,
				},
			},
		},
		{
			name: "At",
			pos:  position{line: 144, col: 1, offset: 5320},
			expr: &actionExpr{
				pos: position{line: 144, col: 6, offset: 5325},
				run: (*parser).callonAt1,
				expr: &litMatcher{
					pos:        position{line: 144, col: 6, offset: 5325},
					val:        "",
					ignoreCase: false,
					want:       "\"\"",
				},
			},
		},
	},
}

func (c *current) onTemplate1(segs any) (any, error) {
	return templateNode(segs)
}

func (p *parser) callonTemplate1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTemplate1(stack["segs"])
}

func (c *current) onHole1(at, e any) (any, error) {
	return holeNode(at, e)
}

func (p *parser) callonHole1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHole1(stack["at"], stack["e"])
}

func (c *current) onTextRun1(cs any) (any, error) {
	return textNode(cs)
}

func (p *parser) callonTextRun1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTextRun1(stack["cs"])
}

func (c *current) onTextChar1(ch any) (any, error) {
	return str(ch)
}

func (p *parser) callonTextChar1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTextChar1(stack["ch"])
}

func (c *current) onTernary1(cond, t any) (any, error) {
	return ternaryNode(cond, t)
}

func (p *parser) callonTernary1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTernary1(stack["cond"], stack["t"])
}

func (c *current) onCoalesce1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonCoalesce1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoalesce1(stack["h"], stack["t"])
}

func (c *current) onOr1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonOr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1(stack["h"], stack["t"])
}

func (c *current) onAnd1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonAnd1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnd1(stack["h"], stack["t"])
}

func (c *current) onEquality1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonEquality1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEquality1(stack["h"], stack["t"])
}

func (c *current) onRelational1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonRelational1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelational1(stack["h"], stack["t"])
}

func (c *current) onAdditive1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonAdditive1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive1(stack["h"], stack["t"])
}

func (c *current) onMultiplicative1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonMultiplicative1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative1(stack["h"], stack["t"])
}

func (c *current) onUnary2(at, op, operand any) (any, error) {
	return unaryNode(at, op, operand)
}

func (p *parser) callonUnary2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnary2(stack["at"], stack["op"], stack["operand"])
}

func (c *current) onPostfix1(base, sfx any) (any, error) {
	return postfixNode(base, sfx)
}

func (p *parser) callonPostfix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPostfix1(stack["base"], stack["sfx"])
}

func (c *current) onParenExpr1(e any) (any, error) {
	return parenNode(e)
}

func (p *parser) callonParenExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenExpr1(stack["e"])
}

func (c *current) onCoalesceOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonCoalesceOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoalesceOp1(stack["op"])
}

func (c *current) onOrOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonOrOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrOp1(stack["op"])
}

func (c *current) onAndOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonAndOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndOp1(stack["op"])
}

func (c *current) onEqualityOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonEqualityOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualityOp1(stack["op"])
}

func (c *current) onRelationalOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonRelationalOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelationalOp1(stack["op"])
}

func (c *current) onAdditiveOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonAdditiveOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditiveOp1(stack["op"])
}

func (c *current) onMultiplicativeOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonMultiplicativeOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicativeOp1(stack["op"])
}

func (c *current) onUnaryOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonUnaryOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaryOp1(stack["op"])
}

func (c *current) onMemberSuffix1(at, n any) (any, error) {
	return memberSuffix(at, n)
}

func (p *parser) callonMemberSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMemberSuffix1(stack["at"], stack["n"])
}

func (c *current) onProjectSuffix1(at any) (any, error) {
	return projectSuffix(at)
}

func (p *parser) callonProjectSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProjectSuffix1(stack["at"])
}

func (c *current) onIndexSuffix1(at, e any) (any, error) {
	return indexSuffix(at, e)
}

func (p *parser) callonIndexSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexSuffix1(stack["at"], stack["e"])
}

func (c *current) onCallSuffix1(at, args any) (any, error) {
	return callSuffix(at, args)
}

func (p *parser) callonCallSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallSuffix1(stack["at"], stack["args"])
}

func (c *current) onArgs1(h, t any) (any, error) {
	return argList(h, t)
}

func (p *parser) callonArgs1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgs1(stack["h"], stack["t"])
}

func (c *current) onNameRef1(at, n any) (any, error) {
	return nameNode(at, n)
}

func (p *parser) callonNameRef1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNameRef1(stack["at"], stack["n"])
}

func (c *current) onName1(h, t any) (any, error) {
	return str(h, t)
}

func (p *parser) callonName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onName1(stack["h"], stack["t"])
}

func (c *current) onNullLit1(at any) (any, error) {
	return nullNode(at)
}

func (p *parser) callonNullLit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNullLit1(stack["at"])
}

func (c *current) onBoolLit1(at, v any) (any, error) {
	return boolNode(at, v)
}

func (p *parser) callonBoolLit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolLit1(stack["at"], stack["v"])
}

func (c *current) onNumberLit1(at, i, f, e any) (any, error) {
	return numberNode(at, i, f, e)
}

func (p *parser) callonNumberLit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberLit1(stack["at"], stack["i"], stack["f"], stack["e"])
}

func (c *current) onDigits1(d any) (any, error) {
	return str(d)
}

func (p *parser) callonDigits1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDigits1(stack["d"])
}

func (c *current) onFrac1(d any) (any, error) {
	return str(".", d)
}

func (p *parser) callonFrac1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFrac1(stack["d"])
}

func (c *current) onExp1(e, s, d any) (any, error) {
	return str(e, s, d)
}

func (p *parser) callonExp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExp1(stack["e"], stack["s"], stack["d"])
}

func (c *current) onStringLit2(at, cs any) (any, error) {
	return stringNode(at, cs)
}

func (p *parser) callonStringLit2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLit2(stack["at"], stack["cs"])
}

func (c *current) onStringLit11(at, cs any) (any, error) {
	return stringNode(at, cs)
}

func (p *parser) callonStringLit11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLit11(stack["at"], stack["cs"])
}

func (c *current) onSqChar3(ch any) (any, error) {
	return str(ch)
}

func (p *parser) callonSqChar3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSqChar3(stack["ch"])
}

func (c *current) onDqChar3(ch any) (any, error) {
	return str(ch)
}

func (p *parser) callonDqChar3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDqChar3(stack["ch"])
}

func (c *current) onEscape1(ch any) (any, error) {
	return escapeChar(ch)
}

func (p *parser) callonEscape1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape1(stack["ch"])
}

func (c *current) onAt1() (any, error) {
	return c.pos.offset, nil
}

func (p *parser) callonAt1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAt1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
