// Code generated by pigeon; DO NOT EDIT.

// Code generated by tools/expression. DO NOT EDIT.
package expressions

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Template",
			pos:  position{line: 28, col: 1, offset: 1204},
			expr: &actionExpr{
				pos: position{line: 28, col: 12, offset: 1215},
				run: (*parser).callonTemplate1,
				expr: &seqExpr{
					pos: position{line: 28, col: 12, offset: 1215},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 28, col: 12, offset: 1215},
							label: "segs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 28, col: 17, offset: 1220},
								expr: &ruleRefExpr{
									pos:  position{line: 28, col: 17, offset: 1220},
									name: "Segment",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 28, col: 26, offset: 1229},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Segment",
			pos:  position{line: 30, col: 1, offset: 1264},
			expr: &choiceExpr{
				pos: position{line: 30, col: 11, offset: 1274},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 30, col: 11, offset: 1274},
						name: "Hole",
					},
					&ruleRefExpr{
						pos:  position{line: 30, col: 18, offset: 1281},
						name: "TextRun",
					},
				},
			},
		},
		{
			name: "Hole",
			pos:  position{line: 32, col: 1, offset: 1290},
			expr: &actionExpr{
				pos: position{line: 32, col: 8, offset: 1297},
				run: (*parser).callonHole1,
				expr: &seqExpr{
					pos: position{line: 32, col: 8, offset: 1297},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 32, col: 8, offset: 1297},
							val:        "{{",
							ignoreCase: false,
							want:       "\"{{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 13, offset: 1302},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 15, offset: 1304},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 18, offset: 1307},
								name: "At",
							},
						},
						&labeledExpr{
							pos:   position{line: 32, col: 21, offset: 1310},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 23, offset: 1312},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 28, offset: 1317},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 32, col: 30, offset: 1319},
							val:        "}}",
							ignoreCase: false,
							want:       "\"}}\"",
						},
					},
				},
			},
		},
		{
			name: "TextRun",
			pos:  position{line: 34, col: 1, offset: 1352},
			expr: &actionExpr{
				pos: position{line: 34, col: 11, offset: 1362},
				run: (*parser).callonTextRun1,
				expr: &labeledExpr{
					pos:   position{line: 34, col: 11, offset: 1362},
					label: "cs",
					expr: &oneOrMoreExpr{
						pos: position{line: 34, col: 14, offset: 1365},
						expr: &ruleRefExpr{
							pos:  position{line: 34, col: 14, offset: 1365},
							name: "TextChar",
						},
					},
				},
			},
		},
		{
			name: "TextChar",
			pos:  position{line: 36, col: 1, offset: 1400},
			expr: &actionExpr{
				pos: position{line: 36, col: 12, offset: 1411},
				run: (*parser).callonTextChar1,
				expr: &seqExpr{
					pos: position{line: 36, col: 12, offset: 1411},
					exprs: []any{
						&notExpr{
							pos: position{line: 36, col: 12, offset: 1411},
							expr: &litMatcher{
								pos:        position{line: 36, col: 13, offset: 1412},
								val:        "{{",
								ignoreCase: false,
								want:       "\"{{\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 36, col: 18, offset: 1417},
							label: "ch",
							expr: &anyMatcher{
								line: 36, col: 21, offset: 1420,
							},
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 40, col: 1, offset: 1523},
			expr: &ruleRefExpr{
				pos:  position{line: 40, col: 8, offset: 1530},
				name: "Ternary",
			},
		},
		{
			name: "ExpressionEntry",
			pos:  position{line: 50, col: 1, offset: 2064},
			expr: &actionExpr{
				pos: position{line: 50, col: 19, offset: 2082},
				run: (*parser).callonExpressionEntry1,
				expr: &seqExpr{
					pos: position{line: 50, col: 19, offset: 2082},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 50, col: 19, offset: 2082},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 21, offset: 2084},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 26, offset: 2089},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Ternary",
			pos:  position{line: 52, col: 1, offset: 2118},
			expr: &actionExpr{
				pos: position{line: 52, col: 11, offset: 2128},
				run: (*parser).callonTernary1,
				expr: &seqExpr{
					pos: position{line: 52, col: 11, offset: 2128},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 52, col: 11, offset: 2128},
							label: "cond",
							expr: &ruleRefExpr{
								pos:  position{line: 52, col: 16, offset: 2133},
								name: "Coalesce",
							},
						},
						&labeledExpr{
							pos:   position{line: 52, col: 25, offset: 2142},
							label: "t",
							expr: &zeroOrOneExpr{
								pos: position{line: 52, col: 27, offset: 2144},
								expr: &seqExpr{
									pos: position{line: 52, col: 29, offset: 2146},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 52, col: 29, offset: 2146},
											name: "QMark",
										},
										&ruleRefExpr{
											pos:  position{line: 52, col: 35, offset: 2152},
											name: "Ternary",
										},
										&ruleRefExpr{
											pos:  position{line: 52, col: 43, offset: 2160},
											name: "Colon",
										},
										&ruleRefExpr{
											pos:  position{line: 52, col: 49, offset: 2166},
											name: "Ternary",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Coalesce",
			pos:  position{line: 54, col: 1, offset: 2210},
			expr: &actionExpr{
				pos: position{line: 54, col: 12, offset: 2221},
				run: (*parser).callonCoalesce1,
				expr: &seqExpr{
					pos: position{line: 54, col: 12, offset: 2221},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 54, col: 12, offset: 2221},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 14, offset: 2223},
								name: "Or",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 17, offset: 2226},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 54, col: 19, offset: 2228},
								expr: &seqExpr{
									pos: position{line: 54, col: 21, offset: 2230},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 54, col: 21, offset: 2230},
											name: "CoalesceOp",
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 32, offset: 2241},
											name: "Or",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Or",
			pos:  position{line: 56, col: 1, offset: 2276},
			expr: &actionExpr{
				pos: position{line: 56, col: 6, offset: 2281},
				run: (*parser).callonOr1,
				expr: &seqExpr{
					pos: position{line: 56, col: 6, offset: 2281},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 56, col: 6, offset: 2281},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 8, offset: 2283},
								name: "And",
							},
						},
						&labeledExpr{
							pos:   position{line: 56, col: 12, offset: 2287},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 56, col: 14, offset: 2289},
								expr: &seqExpr{
									pos: position{line: 56, col: 16, offset: 2291},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 56, col: 16, offset: 2291},
											name: "OrOp",
										},
										&ruleRefExpr{
											pos:  position{line: 56, col: 21, offset: 2296},
											name: "And",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "And",
			pos:  position{line: 58, col: 1, offset: 2332},
			expr: &actionExpr{
				pos: position{line: 58, col: 7, offset: 2338},
				run: (*parser).callonAnd1,
				expr: &seqExpr{
					pos: position{line: 58, col: 7, offset: 2338},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 58, col: 7, offset: 2338},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 58, col: 9, offset: 2340},
								name: "Equality",
							},
						},
						&labeledExpr{
							pos:   position{line: 58, col: 18, offset: 2349},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 58, col: 20, offset: 2351},
								expr: &seqExpr{
									pos: position{line: 58, col: 22, offset: 2353},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 58, col: 22, offset: 2353},
											name: "AndOp",
										},
										&ruleRefExpr{
											pos:  position{line: 58, col: 28, offset: 2359},
											name: "Equality",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Equality",
			pos:  position{line: 60, col: 1, offset: 2400},
			expr: &actionExpr{
				pos: position{line: 60, col: 12, offset: 2411},
				run: (*parser).callonEquality1,
				expr: &seqExpr{
					pos: position{line: 60, col: 12, offset: 2411},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 60, col: 12, offset: 2411},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 60, col: 14, offset: 2413},
								name: "Relational",
							},
						},
						&labeledExpr{
							pos:   position{line: 60, col: 25, offset: 2424},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 60, col: 27, offset: 2426},
								expr: &seqExpr{
									pos: position{line: 60, col: 29, offset: 2428},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 60, col: 29, offset: 2428},
											name: "EqualityOp",
										},
										&ruleRefExpr{
											pos:  position{line: 60, col: 40, offset: 2439},
											name: "Relational",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Relational",
			pos:  position{line: 62, col: 1, offset: 2482},
			expr: &actionExpr{
				pos: position{line: 62, col: 14, offset: 2495},
				run: (*parser).callonRelational1,
				expr: &seqExpr{
					pos: position{line: 62, col: 14, offset: 2495},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 62, col: 14, offset: 2495},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 62, col: 16, offset: 2497},
								name: "Additive",
							},
						},
						&labeledExpr{
							pos:   position{line: 62, col: 25, offset: 2506},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 62, col: 27, offset: 2508},
								expr: &seqExpr{
									pos: position{line: 62, col: 29, offset: 2510},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 62, col: 29, offset: 2510},
											name: "RelationalOp",
										},
										&ruleRefExpr{
											pos:  position{line: 62, col: 42, offset: 2523},
											name: "Additive",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Additive",
			pos:  position{line: 64, col: 1, offset: 2564},
			expr: &actionExpr{
				pos: position{line: 64, col: 12, offset: 2575},
				run: (*parser).callonAdditive1,
				expr: &seqExpr{
					pos: position{line: 64, col: 12, offset: 2575},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 64, col: 12, offset: 2575},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 64, col: 14, offset: 2577},
								name: "Multiplicative",
							},
						},
						&labeledExpr{
							pos:   position{line: 64, col: 29, offset: 2592},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 64, col: 31, offset: 2594},
								expr: &seqExpr{
									pos: position{line: 64, col: 33, offset: 2596},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 64, col: 33, offset: 2596},
											name: "AdditiveOp",
										},
										&ruleRefExpr{
											pos:  position{line: 64, col: 44, offset: 2607},
											name: "Multiplicative",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Multiplicative",
			pos:  position{line: 66, col: 1, offset: 2654},
			expr: &actionExpr{
				pos: position{line: 66, col: 18, offset: 2671},
				run: (*parser).callonMultiplicative1,
				expr: &seqExpr{
					pos: position{line: 66, col: 18, offset: 2671},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 66, col: 18, offset: 2671},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 66, col: 20, offset: 2673},
								name: "Unary",
							},
						},
						&labeledExpr{
							pos:   position{line: 66, col: 26, offset: 2679},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 66, col: 28, offset: 2681},
								expr: &seqExpr{
									pos: position{line: 66, col: 30, offset: 2683},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 66, col: 30, offset: 2683},
											name: "MultiplicativeOp",
										},
										&ruleRefExpr{
											pos:  position{line: 66, col: 47, offset: 2700},
											name: "Unary",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Unary",
			pos:  position{line: 68, col: 1, offset: 2738},
			expr: &choiceExpr{
				pos: position{line: 68, col: 9, offset: 2746},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 68, col: 9, offset: 2746},
						run: (*parser).callonUnary2,
						expr: &seqExpr{
							pos: position{line: 68, col: 9, offset: 2746},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 68, col: 9, offset: 2746},
									label: "at",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 12, offset: 2749},
										name: "At",
									},
								},
								&labeledExpr{
									pos:   position{line: 68, col: 15, offset: 2752},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 18, offset: 2755},
										name: "UnaryOp",
									},
								},
								&labeledExpr{
									pos:   position{line: 68, col: 26, offset: 2763},
									label: "operand",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 34, offset: 2771},
										name: "Unary",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 69, col: 9, offset: 2823},
						name: "Postfix",
					},
				},
			},
		},
		{
			name: "Postfix",
			pos:  position{line: 71, col: 1, offset: 2832},
			expr: &actionExpr{
				pos: position{line: 71, col: 11, offset: 2842},
				run: (*parser).callonPostfix1,
				expr: &seqExpr{
					pos: position{line: 71, col: 11, offset: 2842},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 71, col: 11, offset: 2842},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 71, col: 16, offset: 2847},
								name: "Primary",
							},
						},
						&labeledExpr{
							pos:   position{line: 71, col: 24, offset: 2855},
							label: "sfx",
							expr: &zeroOrMoreExpr{
								pos: position{line: 71, col: 28, offset: 2859},
								expr: &ruleRefExpr{
									pos:  position{line: 71, col: 28, offset: 2859},
									name: "Suffix",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Primary",
			pos:  position{line: 73, col: 1, offset: 2902},
			expr: &choiceExpr{
				pos: position{line: 73, col: 11, offset: 2912},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 73, col: 11, offset: 2912},
						name: "ParenExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 74, col: 11, offset: 2932},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 75, col: 11, offset: 2950},
						name: "NameRef",
					},
				},
			},
		},
		{
			name: "ParenExpr",
			pos:  position{line: 77, col: 1, offset: 2959},
			expr: &actionExpr{
				pos: position{line: 77, col: 13, offset: 2971},
				run: (*parser).callonParenExpr1,
				expr: &seqExpr{
					pos: position{line: 77, col: 13, offset: 2971},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 77, col: 13, offset: 2971},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 77, col: 17, offset: 2975},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 77, col: 19, offset: 2977},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 77, col: 21, offset: 2979},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 77, col: 26, offset: 2984},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 77, col: 28, offset: 2986},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "QMark",
			pos:  position{line: 84, col: 1, offset: 3258},
			expr: &seqExpr{
				pos: position{line: 84, col: 9, offset: 3266},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 84, col: 9, offset: 3266},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 84, col: 11, offset: 3268},
						val:        "?",
						ignoreCase: false,
						want:       "\"?\"",
					},
					&notExpr{
						pos: position{line: 84, col: 15, offset: 3272},
						expr: &litMatcher{
							pos:        position{line: 84, col: 16, offset: 3273},
							val:        "?",
							ignoreCase: false,
							want:       "\"?\"",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 84, col: 20, offset: 3277},
						name: "_",
					},
				},
			},
		},
		{
			name: "Colon",
			pos:  position{line: 85, col: 1, offset: 3279},
			expr: &seqExpr{
				pos: position{line: 85, col: 9, offset: 3287},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 85, col: 9, offset: 3287},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 85, col: 11, offset: 3289},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
					&ruleRefExpr{
						pos:  position{line: 85, col: 15, offset: 3293},
						name: "_",
					},
				},
			},
		},
		{
			name: "CoalesceOp",
			pos:  position{line: 87, col: 1, offset: 3296},
			expr: &actionExpr{
				pos: position{line: 87, col: 20, offset: 3315},
				run: (*parser).callonCoalesceOp1,
				expr: &seqExpr{
					pos: position{line: 87, col: 20, offset: 3315},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 87, col: 20, offset: 3315},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 87, col: 22, offset: 3317},
							label: "op",
							expr: &litMatcher{
								pos:        position{line: 87, col: 25, offset: 3320},
								val:        "??",
								ignoreCase: false,
								want:       "\"??\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 87, col: 30, offset: 3325},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "OrOp",
			pos:  position{line: 88, col: 1, offset: 3378},
			expr: &actionExpr{
				pos: position{line: 88, col: 20, offset: 3397},
				run: (*parser).callonOrOp1,
				expr: &seqExpr{
					pos: position{line: 88, col: 20, offset: 3397},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 88, col: 20, offset: 3397},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 88, col: 22, offset: 3399},
							label: "op",
							expr: &litMatcher{
								pos:        position{line: 88, col: 25, offset: 3402},
								val:        "||",
								ignoreCase: false,
								want:       "\"||\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 88, col: 30, offset: 3407},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "AndOp",
			pos:  position{line: 89, col: 1, offset: 3460},
			expr: &actionExpr{
				pos: position{line: 89, col: 20, offset: 3479},
				run: (*parser).callonAndOp1,
				expr: &seqExpr{
					pos: position{line: 89, col: 20, offset: 3479},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 89, col: 20, offset: 3479},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 89, col: 22, offset: 3481},
							label: "op",
							expr: &litMatcher{
								pos:        position{line: 89, col: 25, offset: 3484},
								val:        "&&",
								ignoreCase: false,
								want:       "\"&&\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 89, col: 30, offset: 3489},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "EqualityOp",
			pos:  position{line: 90, col: 1, offset: 3542},
			expr: &actionExpr{
				pos: position{line: 90, col: 20, offset: 3561},
				run: (*parser).callonEqualityOp1,
				expr: &seqExpr{
					pos: position{line: 90, col: 20, offset: 3561},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 90, col: 20, offset: 3561},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 90, col: 22, offset: 3563},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 90, col: 26, offset: 3567},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 90, col: 26, offset: 3567},
										val:        "==",
										ignoreCase: false,
										want:       "\"==\"",
									},
									&litMatcher{
										pos:        position{line: 90, col: 33, offset: 3574},
										val:        "!=",
										ignoreCase: false,
										want:       "\"!=\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 90, col: 39, offset: 3580},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "RelationalOp",
			pos:  position{line: 91, col: 1, offset: 3624},
			expr: &actionExpr{
				pos: position{line: 91, col: 20, offset: 3643},
				run: (*parser).callonRelationalOp1,
				expr: &seqExpr{
					pos: position{line: 91, col: 20, offset: 3643},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 91, col: 20, offset: 3643},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 91, col: 22, offset: 3645},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 91, col: 26, offset: 3649},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 91, col: 26, offset: 3649},
										val:        "<=",
										ignoreCase: false,
										want:       "\"<=\"",
									},
									&litMatcher{
										pos:        position{line: 91, col: 33, offset: 3656},
										val:        ">=",
										ignoreCase: false,
										want:       "\">=\"",
									},
									&litMatcher{
										pos:        position{line: 91, col: 40, offset: 3663},
										val:        "<",
										ignoreCase: false,
										want:       "\"<\"",
									},
									&litMatcher{
										pos:        position{line: 91, col: 46, offset: 3669},
										val:        ">",
										ignoreCase: false,
										want:       "\">\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 91, col: 51, offset: 3674},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "AdditiveOp",
			pos:  position{line: 92, col: 1, offset: 3706},
			expr: &actionExpr{
				pos: position{line: 92, col: 20, offset: 3725},
				run: (*parser).callonAdditiveOp1,
				expr: &seqExpr{
					pos: position{line: 92, col: 20, offset: 3725},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 92, col: 20, offset: 3725},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 92, col: 22, offset: 3727},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 92, col: 26, offset: 3731},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 92, col: 26, offset: 3731},
										val:        "+",
										ignoreCase: false,
										want:       "\"+\"",
									},
									&litMatcher{
										pos:        position{line: 92, col: 32, offset: 3737},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 92, col: 37, offset: 3742},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "MultiplicativeOp",
			pos:  position{line: 93, col: 1, offset: 3788},
			expr: &actionExpr{
				pos: position{line: 93, col: 20, offset: 3807},
				run: (*parser).callonMultiplicativeOp1,
				expr: &seqExpr{
					pos: position{line: 93, col: 20, offset: 3807},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 93, col: 20, offset: 3807},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 93, col: 22, offset: 3809},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 93, col: 26, offset: 3813},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 93, col: 26, offset: 3813},
										val:        "*",
										ignoreCase: false,
										want:       "\"*\"",
									},
									&litMatcher{
										pos:        position{line: 93, col: 32, offset: 3819},
										val:        "/",
										ignoreCase: false,
										want:       "\"/\"",
									},
									&litMatcher{
										pos:        position{line: 93, col: 38, offset: 3825},
										val:        "%",
										ignoreCase: false,
										want:       "\"%\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 93, col: 43, offset: 3830},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "UnaryOp",
			pos:  position{line: 94, col: 1, offset: 3870},
			expr: &actionExpr{
				pos: position{line: 94, col: 20, offset: 3889},
				run: (*parser).callonUnaryOp1,
				expr: &seqExpr{
					pos: position{line: 94, col: 20, offset: 3889},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 94, col: 20, offset: 3889},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 94, col: 24, offset: 3893},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 94, col: 24, offset: 3893},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 94, col: 24, offset: 3893},
												val:        "!",
												ignoreCase: false,
												want:       "\"!\"",
											},
											&notExpr{
												pos: position{line: 94, col: 28, offset: 3897},
												expr: &litMatcher{
													pos:        position{line: 94, col: 29, offset: 3898},
													val:        "=",
													ignoreCase: false,
													want:       "\"=\"",
												},
											},
										},
									},
									&litMatcher{
										pos:        position{line: 94, col: 35, offset: 3904},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 40, offset: 3909},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Suffix",
			pos:  position{line: 98, col: 1, offset: 4034},
			expr: &choiceExpr{
				pos: position{line: 98, col: 10, offset: 4043},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 98, col: 10, offset: 4043},
						name: "MemberSuffix",
					},
					&ruleRefExpr{
						pos:  position{line: 98, col: 25, offset: 4058},
						name: "ProjectSuffix",
					},
					&ruleRefExpr{
						pos:  position{line: 98, col: 41, offset: 4074},
						name: "IndexSuffix",
					},
					&ruleRefExpr{
						pos:  position{line: 98, col: 55, offset: 4088},
						name: "CallSuffix",
					},
				},
			},
		},
		{
			name: "MemberSuffix",
			pos:  position{line: 100, col: 1, offset: 4100},
			expr: &actionExpr{
				pos: position{line: 100, col: 17, offset: 4116},
				run: (*parser).callonMemberSuffix1,
				expr: &seqExpr{
					pos: position{line: 100, col: 17, offset: 4116},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 100, col: 17, offset: 4116},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 20, offset: 4119},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 100, col: 23, offset: 4122},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 100, col: 27, offset: 4126},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 100, col: 29, offset: 4128},
								name: "Name",
							},
						},
					},
				},
			},
		},
		{
			name: "ProjectSuffix",
			pos:  position{line: 101, col: 1, offset: 4186},
			expr: &actionExpr{
				pos: position{line: 101, col: 17, offset: 4202},
				run: (*parser).callonProjectSuffix1,
				expr: &seqExpr{
					pos: position{line: 101, col: 17, offset: 4202},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 101, col: 17, offset: 4202},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 20, offset: 4205},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 101, col: 23, offset: 4208},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 101, col: 27, offset: 4212},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 101, col: 29, offset: 4214},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "IndexSuffix",
			pos:  position{line: 102, col: 1, offset: 4270},
			expr: &actionExpr{
				pos: position{line: 102, col: 17, offset: 4286},
				run: (*parser).callonIndexSuffix1,
				expr: &seqExpr{
					pos: position{line: 102, col: 17, offset: 4286},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 102, col: 17, offset: 4286},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 102, col: 20, offset: 4289},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 102, col: 23, offset: 4292},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 102, col: 27, offset: 4296},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 102, col: 29, offset: 4298},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 102, col: 31, offset: 4300},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 102, col: 36, offset: 4305},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 102, col: 38, offset: 4307},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "CallSuffix",
			pos:  position{line: 103, col: 1, offset: 4355},
			expr: &actionExpr{
				pos: position{line: 103, col: 17, offset: 4371},
				run: (*parser).callonCallSuffix1,
				expr: &seqExpr{
					pos: position{line: 103, col: 17, offset: 4371},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 103, col: 17, offset: 4371},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 20, offset: 4374},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 103, col: 23, offset: 4377},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 103, col: 27, offset: 4381},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 103, col: 29, offset: 4383},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 103, col: 34, offset: 4388},
								expr: &ruleRefExpr{
									pos:  position{line: 103, col: 34, offset: 4388},
									name: "Args",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 103, col: 40, offset: 4394},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 103, col: 42, offset: 4396},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Args",
			pos:  position{line: 105, col: 1, offset: 4443},
			expr: &actionExpr{
				pos: position{line: 105, col: 8, offset: 4450},
				run: (*parser).callonArgs1,
				expr: &seqExpr{
					pos: position{line: 105, col: 8, offset: 4450},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 105, col: 8, offset: 4450},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 105, col: 10, offset: 4452},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 105, col: 15, offset: 4457},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 105, col: 17, offset: 4459},
								expr: &seqExpr{
									pos: position{line: 105, col: 19, offset: 4461},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 105, col: 19, offset: 4461},
											name: "Comma",
										},
										&ruleRefExpr{
											pos:  position{line: 105, col: 25, offset: 4467},
											name: "Expr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Comma",
			pos:  position{line: 107, col: 1, offset: 4501},
			expr: &seqExpr{
				pos: position{line: 107, col: 9, offset: 4509},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 107, col: 9, offset: 4509},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 107, col: 11, offset: 4511},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&ruleRefExpr{
						pos:  position{line: 107, col: 15, offset: 4515},
						name: "_",
					},
				},
			},
		},
		{
			name: "NameRef",
			pos:  position{line: 111, col: 1, offset: 4599},
			expr: &actionExpr{
				pos: position{line: 111, col: 11, offset: 4609},
				run: (*parser).callonNameRef1,
				expr: &seqExpr{
					pos: position{line: 111, col: 11, offset: 4609},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 111, col: 11, offset: 4609},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 14, offset: 4612},
								name: "At",
							},
						},
						&notExpr{
							pos: position{line: 111, col: 17, offset: 4615},
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 18, offset: 4616},
								name: "ReservedWord",
							},
						},
						&labeledExpr{
							pos:   position{line: 111, col: 31, offset: 4629},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 33, offset: 4631},
								name: "Name",
							},
						},
					},
				},
			},
		},
		{
			name: "Name",
			pos:  position{line: 113, col: 1, offset: 4664},
			expr: &actionExpr{
				pos: position{line: 113, col: 8, offset: 4671},
				run: (*parser).callonName1,
				expr: &seqExpr{
					pos: position{line: 113, col: 8, offset: 4671},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 113, col: 8, offset: 4671},
							label: "h",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 10, offset: 4673},
								name: "NameStart",
							},
						},
						&labeledExpr{
							pos:   position{line: 113, col: 20, offset: 4683},
							label: "t",
							expr: &zeroOrMoreExpr{
								pos: position{line: 113, col: 22, offset: 4685},
								expr: &ruleRefExpr{
									pos:  position{line: 113, col: 22, offset: 4685},
									name: "NamePart",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NameStart",
			pos:  position{line: 115, col: 1, offset: 4717},
			expr: &charClassMatcher{
				pos:        position{line: 115, col: 13, offset: 4729},
				val:        "[a-zA-Z_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NamePart",
			pos:  position{line: 116, col: 1, offset: 4739},
			expr: &charClassMatcher{
				pos:        position{line: 116, col: 13, offset: 4751},
				val:        "[a-zA-Z0-9_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "ReservedWord",
			pos:  position{line: 118, col: 1, offset: 4765},
			expr: &seqExpr{
				pos: position{line: 118, col: 16, offset: 4780},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 118, col: 17, offset: 4781},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 118, col: 17, offset: 4781},
								val:        "true",
								ignoreCase: false,
								want:       "\"true\"",
							},
							&litMatcher{
								pos:        position{line: 118, col: 26, offset: 4790},
								val:        "false",
								ignoreCase: false,
								want:       "\"false\"",
							},
							&litMatcher{
								pos:        position{line: 118, col: 36, offset: 4800},
								val:        "null",
								ignoreCase: false,
								want:       "\"null\"",
							},
						},
					},
					&notExpr{
						pos: position{line: 118, col: 44, offset: 4808},
						expr: &ruleRefExpr{
							pos:  position{line: 118, col: 45, offset: 4809},
							name: "NamePart",
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 122, col: 1, offset: 4900},
			expr: &choiceExpr{
				pos: position{line: 122, col: 11, offset: 4910},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 122, col: 11, offset: 4910},
						name: "NullLit",
					},
					&ruleRefExpr{
						pos:  position{line: 122, col: 21, offset: 4920},
						name: "BoolLit",
					},
					&ruleRefExpr{
						pos:  position{line: 122, col: 31, offset: 4930},
						name: "NumberLit",
					},
					&ruleRefExpr{
						pos:  position{line: 122, col: 43, offset: 4942},
						name: "StringLit",
					},
				},
			},
		},
		{
			name: "NullLit",
			pos:  position{line: 124, col: 1, offset: 4953},
			expr: &actionExpr{
				pos: position{line: 124, col: 11, offset: 4963},
				run: (*parser).callonNullLit1,
				expr: &seqExpr{
					pos: position{line: 124, col: 11, offset: 4963},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 124, col: 11, offset: 4963},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 124, col: 14, offset: 4966},
								name: "At",
							},
						},
						&litMatcher{
							pos:        position{line: 124, col: 17, offset: 4969},
							val:        "null",
							ignoreCase: false,
							want:       "\"null\"",
						},
						&notExpr{
							pos: position{line: 124, col: 24, offset: 4976},
							expr: &ruleRefExpr{
								pos:  position{line: 124, col: 25, offset: 4977},
								name: "NamePart",
							},
						},
					},
				},
			},
		},
		{
			name: "BoolLit",
			pos:  position{line: 125, col: 1, offset: 5023},
			expr: &actionExpr{
				pos: position{line: 125, col: 11, offset: 5033},
				run: (*parser).callonBoolLit1,
				expr: &seqExpr{
					pos: position{line: 125, col: 11, offset: 5033},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 125, col: 11, offset: 5033},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 14, offset: 5036},
								name: "At",
							},
						},
						&labeledExpr{
							pos:   position{line: 125, col: 17, offset: 5039},
							label: "v",
							expr: &choiceExpr{
								pos: position{line: 125, col: 20, offset: 5042},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 125, col: 20, offset: 5042},
										val:        "true",
										ignoreCase: false,
										want:       "\"true\"",
									},
									&litMatcher{
										pos:        position{line: 125, col: 29, offset: 5051},
										val:        "false",
										ignoreCase: false,
										want:       "\"false\"",
									},
								},
							},
						},
						&notExpr{
							pos: position{line: 125, col: 38, offset: 5060},
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 39, offset: 5061},
								name: "NamePart",
							},
						},
					},
				},
			},
		},
		{
			name: "NumberLit",
			pos:  position{line: 127, col: 1, offset: 5098},
			expr: &actionExpr{
				pos: position{line: 127, col: 13, offset: 5110},
				run: (*parser).callonNumberLit1,
				expr: &seqExpr{
					pos: position{line: 127, col: 13, offset: 5110},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 127, col: 13, offset: 5110},
							label: "at",
							expr: &ruleRefExpr{
								pos:  position{line: 127, col: 16, offset: 5113},
								name: "At",
							},
						},
						&labeledExpr{
							pos:   position{line: 127, col: 19, offset: 5116},
							label: "i",
							expr: &ruleRefExpr{
								pos:  position{line: 127, col: 21, offset: 5118},
								name: "Digits",
							},
						},
						&labeledExpr{
							pos:   position{line: 127, col: 28, offset: 5125},
							label: "f",
							expr: &zeroOrOneExpr{
								pos: position{line: 127, col: 30, offset: 5127},
								expr: &ruleRefExpr{
									pos:  position{line: 127, col: 30, offset: 5127},
									name: "Frac",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 127, col: 36, offset: 5133},
							label: "e",
							expr: &zeroOrOneExpr{
								pos: position{line: 127, col: 38, offset: 5135},
								expr: &ruleRefExpr{
									pos:  position{line: 127, col: 38, offset: 5135},
									name: "Exp",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Digits",
			pos:  position{line: 129, col: 1, offset: 5176},
			expr: &actionExpr{
				pos: position{line: 129, col: 10, offset: 5185},
				run: (*parser).callonDigits1,
				expr: &labeledExpr{
					pos:   position{line: 129, col: 10, offset: 5185},
					label: "d",
					expr: &oneOrMoreExpr{
						pos: position{line: 129, col: 12, offset: 5187},
						expr: &ruleRefExpr{
							pos:  position{line: 129, col: 12, offset: 5187},
							name: "NumPart",
						},
					},
				},
			},
		},
		{
			name: "NumPart",
			pos:  position{line: 130, col: 1, offset: 5214},
			expr: &charClassMatcher{
				pos:        position{line: 130, col: 11, offset: 5224},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Frac",
			pos:  position{line: 131, col: 1, offset: 5230},
			expr: &actionExpr{
				pos: position{line: 131, col: 8, offset: 5237},
				run: (*parser).callonFrac1,
				expr: &seqExpr{
					pos: position{line: 131, col: 8, offset: 5237},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 131, col: 8, offset: 5237},
							val:        ".",
							ignoreCase: false,
							want:       "\".\"",
						},
						&labeledExpr{
							pos:   position{line: 131, col: 12, offset: 5241},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 14, offset: 5243},
								name: "Digits",
							},
						},
					},
				},
			},
		},
		{
			name: "Exp",
			pos:  position{line: 132, col: 1, offset: 5281},
			expr: &actionExpr{
				pos: position{line: 132, col: 8, offset: 5288},
				run: (*parser).callonExp1,
				expr: &seqExpr{
					pos: position{line: 132, col: 8, offset: 5288},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 132, col: 8, offset: 5288},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 10, offset: 5290},
								name: "ExpMark",
							},
						},
						&labeledExpr{
							pos:   position{line: 132, col: 18, offset: 5298},
							label: "s",
							expr: &zeroOrOneExpr{
								pos: position{line: 132, col: 20, offset: 5300},
								expr: &ruleRefExpr{
									pos:  position{line: 132, col: 20, offset: 5300},
									name: "Sign",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 132, col: 26, offset: 5306},
							label: "d",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 28, offset: 5308},
								name: "Digits",
							},
						},
					},
				},
			},
		},
		{
			name: "ExpMark",
			pos:  position{line: 133, col: 1, offset: 5339},
			expr: &charClassMatcher{
				pos:        position{line: 133, col: 11, offset: 5349},
				val:        "[eE]",
				chars:      []rune{'e', 'E'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Sign",
			pos:  position{line: 134, col: 1, offset: 5354},
			expr: &charClassMatcher{
				pos:        position{line: 134, col: 8, offset: 5361},
				val:        "[+-]",
				chars:      []rune{'+', '-'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "StringLit",
			pos:  position{line: 136, col: 1, offset: 5367},
			expr: &choiceExpr{
				pos: position{line: 136, col: 13, offset: 5379},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 136, col: 13, offset: 5379},
						run: (*parser).callonStringLit2,
						expr: &seqExpr{
							pos: position{line: 136, col: 13, offset: 5379},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 136, col: 13, offset: 5379},
									label: "at",
									expr: &ruleRefExpr{
										pos:  position{line: 136, col: 16, offset: 5382},
										name: "At",
									},
								},
								&litMatcher{
									pos:        position{line: 136, col: 19, offset: 5385},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
								&labeledExpr{
									pos:   position{line: 136, col: 23, offset: 5389},
									label: "cs",
									expr: &zeroOrMoreExpr{
										pos: position{line: 136, col: 26, offset: 5392},
										expr: &ruleRefExpr{
											pos:  position{line: 136, col: 26, offset: 5392},
											name: "SqChar",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 136, col: 34, offset: 5400},
									val:        "'",
									ignoreCase: false,
									want:       "\"'\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 137, col: 13, offset: 5448},
						run: (*parser).callonStringLit11,
						expr: &seqExpr{
							pos: position{line: 137, col: 13, offset: 5448},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 137, col: 13, offset: 5448},
									label: "at",
									expr: &ruleRefExpr{
										pos:  position{line: 137, col: 16, offset: 5451},
										name: "At",
									},
								},
								&litMatcher{
									pos:        position{line: 137, col: 19, offset: 5454},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&labeledExpr{
									pos:   position{line: 137, col: 24, offset: 5459},
									label: "cs",
									expr: &zeroOrMoreExpr{
										pos: position{line: 137, col: 27, offset: 5462},
										expr: &ruleRefExpr{
											pos:  position{line: 137, col: 27, offset: 5462},
											name: "DqChar",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 137, col: 35, offset: 5470},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SqChar",
			pos:  position{line: 139, col: 1, offset: 5506},
			expr: &choiceExpr{
				pos: position{line: 139, col: 10, offset: 5515},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 139, col: 10, offset: 5515},
						name: "Escape",
					},
					&actionExpr{
						pos: position{line: 139, col: 19, offset: 5524},
						run: (*parser).callonSqChar3,
						expr: &seqExpr{
							pos: position{line: 139, col: 19, offset: 5524},
							exprs: []any{
								&notExpr{
									pos: position{line: 139, col: 19, offset: 5524},
									expr: &litMatcher{
										pos:        position{line: 139, col: 20, offset: 5525},
										val:        "'",
										ignoreCase: false,
										want:       "\"'\"",
									},
								},
								&notExpr{
									pos: position{line: 139, col: 24, offset: 5529},
									expr: &litMatcher{
										pos:        position{line: 139, col: 25, offset: 5530},
										val:        "\\",
										ignoreCase: false,
										want:       "\"\\\\\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 139, col: 30, offset: 5535},
									label: "ch",
									expr: &anyMatcher{
										line: 139, col: 33, offset: 5538,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DqChar",
			pos:  position{line: 140, col: 1, offset: 5559},
			expr: &choiceExpr{
				pos: position{line: 140, col: 10, offset: 5568},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 140, col: 10, offset: 5568},
						name: "Escape",
					},
					&actionExpr{
						pos: position{line: 140, col: 19, offset: 5577},
						run: (*parser).callonDqChar3,
						expr: &seqExpr{
							pos: position{line: 140, col: 19, offset: 5577},
							exprs: []any{
								&notExpr{
									pos: position{line: 140, col: 19, offset: 5577},
									expr: &litMatcher{
										pos:        position{line: 140, col: 20, offset: 5578},
										val:        "\"",
										ignoreCase: false,
										want:       "\"\\\"\"",
									},
								},
								&notExpr{
									pos: position{line: 140, col: 25, offset: 5583},
									expr: &litMatcher{
										pos:        position{line: 140, col: 26, offset: 5584},
										val:        "\\",
										ignoreCase: false,
										want:       "\"\\\\\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 140, col: 31, offset: 5589},
									label: "ch",
									expr: &anyMatcher{
										line: 140, col: 34, offset: 5592,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Escape",
			pos:  position{line: 142, col: 1, offset: 5614},
			expr: &actionExpr{
				pos: position{line: 142, col: 10, offset: 5623},
				run: (*parser).callonEscape1,
				expr: &seqExpr{
					pos: position{line: 142, col: 10, offset: 5623},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 142, col: 10, offset: 5623},
							val:        "\\",
							ignoreCase: false,
							want:       "\"\\\\\"",
						},
						&labeledExpr{
							pos:   position{line: 142, col: 15, offset: 5628},
							label: "ch",
							expr: &anyMatcher{
								line: 142, col: 18, offset: 5631,
							},
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 146, col: 1, offset: 5741},
			expr: &zeroOrMoreExpr{
				pos: position{line: 146, col: 5, offset: 5745},
				expr: &ruleRefExpr{
					pos:  position{line: 146, col: 5, offset: 5745},
					name: "Space",
				},
			},
		},
		{
			name: "Space",
			pos:  position{line: 147, col: 1, offset: 5752},
			expr: &charClassMatcher{
				pos:        position{line: 147, col: 9, offset: 5760},
				val:        "[ \\t\\r\\n]",
				chars:      []rune{' ', '\t', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 149, col: 1, offset: 5771},
			expr: &notExpr{
				pos: position{line: 149, col: 7, offset: 5777},
				expr: &anyMatcher{
					line: 149, col: 8, offset: 5778,
				},
			},
		},
		{
			name: "At",
			pos:  position{line: 157, col: 1, offset: 6042},
			expr: &actionExpr{
				pos: position{line: 157, col: 6, offset: 6047},
				run: (*parser).callonAt1,
				expr: &litMatcher{
					pos:        position{line: 157, col: 6, offset: 6047},
					val:        "",
					ignoreCase: false,
					want:       "\"\"",
				},
			},
		},
	},
}

func (c *current) onTemplate1(segs any) (any, error) {
	return templateNode(segs)
}

func (p *parser) callonTemplate1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTemplate1(stack["segs"])
}

func (c *current) onHole1(at, e any) (any, error) {
	return holeNode(at, e)
}

func (p *parser) callonHole1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHole1(stack["at"], stack["e"])
}

func (c *current) onTextRun1(cs any) (any, error) {
	return textNode(cs)
}

func (p *parser) callonTextRun1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTextRun1(stack["cs"])
}

func (c *current) onTextChar1(ch any) (any, error) {
	return str(ch)
}

func (p *parser) callonTextChar1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTextChar1(stack["ch"])
}

func (c *current) onExpressionEntry1(e any) (any, error) {
	return parenNode(e)
}

func (p *parser) callonExpressionEntry1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionEntry1(stack["e"])
}

func (c *current) onTernary1(cond, t any) (any, error) {
	return ternaryNode(cond, t)
}

func (p *parser) callonTernary1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTernary1(stack["cond"], stack["t"])
}

func (c *current) onCoalesce1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonCoalesce1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoalesce1(stack["h"], stack["t"])
}

func (c *current) onOr1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonOr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOr1(stack["h"], stack["t"])
}

func (c *current) onAnd1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonAnd1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAnd1(stack["h"], stack["t"])
}

func (c *current) onEquality1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonEquality1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEquality1(stack["h"], stack["t"])
}

func (c *current) onRelational1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonRelational1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelational1(stack["h"], stack["t"])
}

func (c *current) onAdditive1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonAdditive1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive1(stack["h"], stack["t"])
}

func (c *current) onMultiplicative1(h, t any) (any, error) {
	return binaryNode(h, t)
}

func (p *parser) callonMultiplicative1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative1(stack["h"], stack["t"])
}

func (c *current) onUnary2(at, op, operand any) (any, error) {
	return unaryNode(at, op, operand)
}

func (p *parser) callonUnary2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnary2(stack["at"], stack["op"], stack["operand"])
}

func (c *current) onPostfix1(base, sfx any) (any, error) {
	return postfixNode(base, sfx)
}

func (p *parser) callonPostfix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPostfix1(stack["base"], stack["sfx"])
}

func (c *current) onParenExpr1(e any) (any, error) {
	return parenNode(e)
}

func (p *parser) callonParenExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenExpr1(stack["e"])
}

func (c *current) onCoalesceOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonCoalesceOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCoalesceOp1(stack["op"])
}

func (c *current) onOrOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonOrOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrOp1(stack["op"])
}

func (c *current) onAndOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonAndOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndOp1(stack["op"])
}

func (c *current) onEqualityOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonEqualityOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualityOp1(stack["op"])
}

func (c *current) onRelationalOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonRelationalOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRelationalOp1(stack["op"])
}

func (c *current) onAdditiveOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonAdditiveOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditiveOp1(stack["op"])
}

func (c *current) onMultiplicativeOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonMultiplicativeOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicativeOp1(stack["op"])
}

func (c *current) onUnaryOp1(op any) (any, error) {
	return str(op)
}

func (p *parser) callonUnaryOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaryOp1(stack["op"])
}

func (c *current) onMemberSuffix1(at, n any) (any, error) {
	return memberSuffix(at, n)
}

func (p *parser) callonMemberSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMemberSuffix1(stack["at"], stack["n"])
}

func (c *current) onProjectSuffix1(at any) (any, error) {
	return projectSuffix(at)
}

func (p *parser) callonProjectSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onProjectSuffix1(stack["at"])
}

func (c *current) onIndexSuffix1(at, e any) (any, error) {
	return indexSuffix(at, e)
}

func (p *parser) callonIndexSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexSuffix1(stack["at"], stack["e"])
}

func (c *current) onCallSuffix1(at, args any) (any, error) {
	return callSuffix(at, args)
}

func (p *parser) callonCallSuffix1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCallSuffix1(stack["at"], stack["args"])
}

func (c *current) onArgs1(h, t any) (any, error) {
	return argList(h, t)
}

func (p *parser) callonArgs1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgs1(stack["h"], stack["t"])
}

func (c *current) onNameRef1(at, n any) (any, error) {
	return nameNode(at, n)
}

func (p *parser) callonNameRef1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNameRef1(stack["at"], stack["n"])
}

func (c *current) onName1(h, t any) (any, error) {
	return str(h, t)
}

func (p *parser) callonName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onName1(stack["h"], stack["t"])
}

func (c *current) onNullLit1(at any) (any, error) {
	return nullNode(at)
}

func (p *parser) callonNullLit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNullLit1(stack["at"])
}

func (c *current) onBoolLit1(at, v any) (any, error) {
	return boolNode(at, v)
}

func (p *parser) callonBoolLit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolLit1(stack["at"], stack["v"])
}

func (c *current) onNumberLit1(at, i, f, e any) (any, error) {
	return numberNode(at, i, f, e)
}

func (p *parser) callonNumberLit1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumberLit1(stack["at"], stack["i"], stack["f"], stack["e"])
}

func (c *current) onDigits1(d any) (any, error) {
	return str(d)
}

func (p *parser) callonDigits1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDigits1(stack["d"])
}

func (c *current) onFrac1(d any) (any, error) {
	return str(".", d)
}

func (p *parser) callonFrac1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFrac1(stack["d"])
}

func (c *current) onExp1(e, s, d any) (any, error) {
	return str(e, s, d)
}

func (p *parser) callonExp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExp1(stack["e"], stack["s"], stack["d"])
}

func (c *current) onStringLit2(at, cs any) (any, error) {
	return stringNode(at, cs)
}

func (p *parser) callonStringLit2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLit2(stack["at"], stack["cs"])
}

func (c *current) onStringLit11(at, cs any) (any, error) {
	return stringNode(at, cs)
}

func (p *parser) callonStringLit11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLit11(stack["at"], stack["cs"])
}

func (c *current) onSqChar3(ch any) (any, error) {
	return str(ch)
}

func (p *parser) callonSqChar3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSqChar3(stack["ch"])
}

func (c *current) onDqChar3(ch any) (any, error) {
	return str(ch)
}

func (p *parser) callonDqChar3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDqChar3(stack["ch"])
}

func (c *current) onEscape1(ch any) (any, error) {
	return escapeChar(ch)
}

func (p *parser) callonEscape1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEscape1(stack["ch"])
}

func (c *current) onAt1() (any, error) {
	return offsetOf(c)
}

func (p *parser) callonAt1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAt1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
