/**
 * The authored YAML contracts -> both languages.
 *
 * Emitting Go source rather than embedding the YAML is forced, not preferred:
 * `go:embed` cannot reach outside its own module and the Go SDK is a separate
 * module, so a canonical YAML file elsewhere in the repo is simply not
 * embeddable — and a symlink breaks inside module zips and proxies.
 */
import fs from 'node:fs'
import path from 'node:path'
import { parse } from 'yaml'

/**
 * Every type a signature may name. The Component Manifest's output types, plus
 * the two that exist only in the language: `unknown` for a value whose type is
 * not statically knowable, and `null` for the one absent value.
 */
export const VALUE_TYPES = [
  'text',
  'number',
  'boolean',
  'datetime',
  'list',
  'object',
  'item',
  'unknown',
  'null',
]

const BANNER = ['// Code generated by tools/expression. DO NOT EDIT.', '// Source: %s', '']

const q = (value) => JSON.stringify(value)

/** SCREAMING_SNAKE -> PascalCase, for Go identifiers. */
const pascal = (value) =>
  value
    .toLowerCase()
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

/** `datetime` -> `TypeDatetime`, the Go constant declared in value.go. */
const goType = (value) => `Type${value.charAt(0).toUpperCase()}${value.slice(1)}`

// ---- functions -------------------------------------------------------------

export function readFunctions(schemasDir) {
  const dir = path.join(schemasDir, 'functions')
  const specs = []

  for (const file of fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.yaml'))
    .sort()) {
    const doc = parse(fs.readFileSync(path.join(dir, file), 'utf8'))
    if (!doc.namespace) throw new Error(`${file}: missing \`namespace\``)

    for (const fn of doc.functions ?? []) {
      const qualified = `${doc.namespace}.${fn.name}`
      const params = (fn.params ?? []).map((param) => {
        assertType(param.type, `${qualified}(${param.name})`)
        return {
          name: param.name,
          type: param.type,
          optional: param.optional === true,
          variadic: param.variadic === true,
        }
      })

      params.forEach((param, index) => {
        if (param.variadic && index !== params.length - 1) {
          throw new Error(`${qualified}: only the last parameter may be variadic`)
        }
        if (param.optional && params.slice(index).some((p) => !p.optional)) {
          throw new Error(`${qualified}: optional parameters must come last`)
        }
      })

      assertType(fn.returns, `${qualified} returns`)
      specs.push({
        namespace: doc.namespace,
        name: fn.name,
        qualified,
        summary: (fn.summary ?? '').trim(),
        params,
        returns: fn.returns,
      })
    }
  }

  const seen = new Set()
  for (const spec of specs) {
    if (seen.has(spec.qualified)) throw new Error(`${spec.qualified} is declared twice`)
    seen.add(spec.qualified)
  }
  return specs.sort((a, b) => a.qualified.localeCompare(b.qualified))
}

function assertType(value, where) {
  if (!VALUE_TYPES.includes(value)) {
    throw new Error(`${where}: unknown type ${q(value)}; expected one of ${VALUE_TYPES.join(', ')}`)
  }
}

export function functionsToTs(specs) {
  const lines = [
    ...BANNER.map((line) => line.replace('%s', 'schemas/functions/*.yaml')),
    "import type { ValueType } from '../value.js'",
    '',
    'export interface ParamSpec {',
    '  readonly name: string',
    '  readonly type: ValueType',
    '  readonly optional: boolean',
    '  readonly variadic: boolean',
    '}',
    '',
    'export interface FunctionSpec {',
    '  readonly namespace: string',
    '  readonly name: string',
    '  /** `namespace.name` — how an expression addresses it. */',
    '  readonly qualified: string',
    '  readonly summary: string',
    '  readonly params: readonly ParamSpec[]',
    '  readonly returns: ValueType',
    '}',
    '',
    '/**',
    ' * What every implementation is checked against at load time. Neither',
    ' * language may add, rename or re-sign a function on its own.',
    ' */',
    'export const CORE_FUNCTIONS: readonly FunctionSpec[] = [',
  ]

  for (const spec of specs) {
    lines.push('  {')
    lines.push(`    namespace: ${q(spec.namespace)},`)
    lines.push(`    name: ${q(spec.name)},`)
    lines.push(`    qualified: ${q(spec.qualified)},`)
    lines.push(`    summary: ${q(spec.summary)},`)
    lines.push(
      spec.params.length === 0
        ? '    params: [],'
        : `    params: [\n${spec.params
            .map(
              (p) =>
                `      { name: ${q(p.name)}, type: ${q(p.type)}, optional: ${p.optional}, variadic: ${p.variadic} },`,
            )
            .join('\n')}\n    ],`,
    )
    lines.push(`    returns: ${q(spec.returns)},`)
    lines.push('  },')
  }

  lines.push('] as const', '')
  return lines.join('\n')
}

export function functionsToGo(specs) {
  const lines = [
    ...BANNER.map((line) => line.replace('%s', 'schemas/functions/*.yaml')),
    'package expressions',
    '',
    '// ParamSpec is one declared parameter.',
    'type ParamSpec struct {',
    '\tName     string',
    '\tType     ValueType',
    '\tOptional bool',
    '\tVariadic bool',
    '}',
    '',
    '// FunctionSpec is one declared function.',
    'type FunctionSpec struct {',
    '\tNamespace string',
    '\tName      string',
    '\t// Qualified is `namespace.name` — how an expression addresses it.',
    '\tQualified string',
    '\tSummary   string',
    '\tParams    []ParamSpec',
    '\tReturns   ValueType',
    '}',
    '',
    '// CoreFunctionSpecs is what every implementation is checked against at',
    '// load time. Neither language may add, rename or re-sign a function on its',
    '// own. The registry that pairs these with implementations is CoreFunctions().',
    'var CoreFunctionSpecs = []FunctionSpec{',
  ]

  for (const spec of specs) {
    lines.push('\t{')
    lines.push(`\t\tNamespace: ${q(spec.namespace)},`)
    lines.push(`\t\tName:      ${q(spec.name)},`)
    lines.push(`\t\tQualified: ${q(spec.qualified)},`)
    lines.push(`\t\tSummary:   ${q(spec.summary)},`)
    lines.push(
      spec.params.length === 0
        ? '\t\tParams:    []ParamSpec{},'
        : `\t\tParams: []ParamSpec{\n${spec.params
            .map(
              (p) =>
                `\t\t\t{Name: ${q(p.name)}, Type: ${goType(p.type)}, Optional: ${p.optional}, Variadic: ${p.variadic}},`,
            )
            .join('\n')}\n\t\t},`,
    )
    lines.push(`\t\tReturns:   ${goType(spec.returns)},`)
    lines.push('\t},')
  }

  lines.push('}', '')
  return lines.join('\n')
}

// ---- diagnostics -----------------------------------------------------------

export function readDiagnostics(schemasDir) {
  const doc = parse(fs.readFileSync(path.join(schemasDir, 'diagnostics.yaml'), 'utf8'))
  const codes = doc.codes ?? []
  if (codes.length === 0) throw new Error('diagnostics.yaml declares no codes')

  const seen = new Set()
  for (const entry of codes) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(entry.code ?? '')) {
      throw new Error(`diagnostics.yaml: bad code ${q(entry.code)}`)
    }
    if (seen.has(entry.code)) throw new Error(`diagnostics.yaml: ${entry.code} is declared twice`)
    seen.add(entry.code)
    if (!['error', 'warning'].includes(entry.severity)) {
      throw new Error(`${entry.code}: severity must be error or warning`)
    }
    if (!['check', 'eval'].includes(entry.phase)) {
      throw new Error(`${entry.code}: phase must be check or eval`)
    }
    if (!entry.message) throw new Error(`${entry.code}: missing message`)
  }
  return codes
}

export function diagnosticsToTs(codes) {
  const lines = [
    ...BANNER.map((line) => line.replace('%s', 'schemas/diagnostics.yaml')),
    '/** Errors block Publish. Warnings inform and block nothing. */',
    "export type Severity = 'error' | 'warning'",
    '',
    '/** `check` is design time; `eval` is run time. */',
    "export type Phase = 'check' | 'eval'",
    '',
    'export type DiagnosticCode =',
    ...codes.map((entry) => `  | ${q(entry.code)}`),
    '',
    'export interface DiagnosticSpec {',
    '  readonly code: DiagnosticCode',
    '  readonly severity: Severity',
    '  readonly phase: Phase',
    '  /** Template. `{name}` holes are filled by `formatMessage`. */',
    '  readonly message: string',
    '}',
    '',
    '/**',
    ' * Severity is part of the shared contract. A code that errors here and',
    ' * warns in Go would let a workflow publish from one builder and not another.',
    ' */',
    'export const DIAGNOSTICS: Record<DiagnosticCode, DiagnosticSpec> = {',
  ]

  for (const entry of codes) {
    lines.push(
      `  ${entry.code}: { code: ${q(entry.code)}, severity: ${q(entry.severity)}, phase: ${q(entry.phase)}, message: ${q(entry.message)} },`,
    )
  }

  lines.push('}', '')
  return lines.join('\n')
}

export function diagnosticsToGo(codes) {
  const lines = [
    ...BANNER.map((line) => line.replace('%s', 'schemas/diagnostics.yaml')),
    'package expressions',
    '',
    '// Severity says what a diagnostic does: an error blocks Publish, a warning',
    '// informs and blocks nothing.',
    'type Severity string',
    '',
    'const (',
    '\tSeverityError   Severity = "error"',
    '\tSeverityWarning Severity = "warning"',
    ')',
    '',
    '// Phase says when a code can be raised: check is design time, eval is run time.',
    'type Phase string',
    '',
    'const (',
    '\tPhaseCheck Phase = "check"',
    '\tPhaseEval  Phase = "eval"',
    ')',
    '',
    '// Code is a stable diagnostic identifier, shared with TypeScript.',
    'type Code string',
    '',
    'const (',
    ...codes.map((entry) => `\tCode${pascal(entry.code)} Code = ${q(entry.code)}`),
    ')',
    '',
    '// DiagnosticSpec is one declared code.',
    'type DiagnosticSpec struct {',
    '\tCode     Code',
    '\tSeverity Severity',
    '\tPhase    Phase',
    '\t// Message is a template; {name} holes are filled by FormatMessage.',
    '\tMessage  string',
    '}',
    '',
    '// Diagnostics is the declaration. Severity is part of the shared contract:',
    '// a code that errors in TypeScript and warns here would let a workflow',
    '// publish from one builder and not another.',
    'var Diagnostics = map[Code]DiagnosticSpec{',
    ...codes.map(
      (entry) =>
        `\tCode${pascal(entry.code)}: {Code: Code${pascal(entry.code)}, Severity: Severity${entry.severity === 'error' ? 'Error' : 'Warning'}, Phase: Phase${entry.phase === 'check' ? 'Check' : 'Eval'}, Message: ${q(entry.message)}},`,
    ),
    '}',
    '',
  ]
  return lines.join('\n')
}
